### PR TITLE
Changed minimumPingReplySize

### PR DESCRIPTION
**Pull request by Hobbydos**
changed minimumPingReplySize to 56 to be in line with https://github.com/openconfig/gnoi/blob/main/system/system.proto#L176

### CODE REVIEW

**Comment by bstoll** [comment]
I think there are some shortcomings with this test and comparing the correct number of bytes sent and received, but I am not sure this is a correct change.  The number of bytes received should be 8 more than the number sent (this is the size of the ICMP header).  The tests are sending 64 for a minimum, so I would expect to receive 72 bytes in responses.  I don't believe this is clearly documented in the GNOI ping behavior, so if you have a different interpretation I would like to know.  The test transmits 64 bytes, so I expect the response to be at least 64 bytes, so lowering this to 56 doesn't make sense to me.

I am open to reworking this aspect of the test, as I think this could be improved (i.e., `icmpHeaderSize` seems strange).

**Comment by Hobbydos** [comment]
@bstoll, Thanks for the feedback. To preface this I had originally raised [issue 302](https://github.com/openconfig/featureprofiles/issues/302) where I outlined that the testcases which have `minimumPingRequestSize` set are correctly handled. However, when it isn't set, it seems like the default value expected by the testcase is `64bytes`:
```
=== RUN   TestGNOIPing/Check_ping_with_IPv4_destination
    ping_test.go:403: Sent ping request: destination:"192.168.99.99"
        
    ping_test.go:419: Got ping responses: Items: 6
        , Content: [source:"192.168.99.99"  time:4602238  bytes:56  sequence:1  ttl:64 source:"192.168.99.99"  time:3387708  bytes:56  sequence:2  ttl:64 source:"192.168.99.99"  time:4430538  bytes:56  sequence:3  ttl:64 source:"192.168.99.99"  time:3408598  bytes:56  sequence:4  ttl:64 source:"192.168.99.99"  time:4406217  bytes:56  sequence:5  ttl:64 source:"192.168.99.99"  time:20568469  sent:5  received:5  min_time:3387708  avg_time:4047059  max_time:4602238  std_dev:597212
        
    ping_test.go:428: Check each ping reply 1 out of 6.
          source:"192.168.99.99"  time:4602238  bytes:56  sequence:1  ttl:64
    ping_test.go:443: Ping Bytes: got 56, want >= 64
```
When `minimumPingRequestSize` is set, the DUT replies with the appropriate expected value.

**Comment by Hobbydos** [comment]
I don't want to overcomplicate this either, but it seems like different vendors might have different implementations. I was testing with cEOS 4.28.3M and their default is set to 64b. Maybe the best way to handle this is to look for more than 1 singular value (56, 64, might be more)? 
```
 gnoic -a 172.20.20.2:6030 -u admin -p admin --insecure system ping --format json --destination 192.168.99.99 --print-proto --count 2
"172.20.20.2:6030":
gnoi.system.PingRequest
destination:  "192.168.99.99"
count:  2
interval:  1000000000

"172.20.20.2:6030":
gnoi.system.PingResponse
source:  "192.168.99.99"
time:  25000
bytes:  64
sequence:  1
ttl:  64

{
  "target": "172.20.20.2:6030",
  "response": {
    "source": "192.168.99.99",
    "time": 25000,
    "bytes": 64,
    "sequence": 1,
    "ttl": 64
  }
```

**Comment by Hobbydos** [comment]
> I see your point. If we change `minimumPingRequestSize` to 56 as well (as this is explicitly documented), I think that would fix the situation you are describing and keep the other test cases as correct as they can be for now.

That's correct, since the test case looks at `>= minimumPingRequestSize`, this should cover for other vendors who might default to 64 bytes.

**Comment by xw-g** [comment]
@Hobbydos have you made changes based on @bstoll 's comment?

**Comment by Hobbydos** [comment]
> 

I'll add the change to `minimumPingRequestSize` as well. I was just testing the changes to ensure it doesn't fail on different vendor implementations.

**Review by xw-g — APPROVED** [review]

**Comment by xw-g** [comment]
@bstoll to review and merge.

**Comment by bstoll** [comment]
/gcbrun

Thanks, this LGTM.

**Pull request merged**
