### PR TITLE
gNMI-1.2: fix key leafref violations

### PR DESCRIPTION
**Pull request by kjahed**
Modifications to gNMI-1.2 to avoid leafref violations for key leaves:
1- Make sure the key 'name' is configured for default NI
2- For cleanup, delete the entire (BGP, ISIS) Protocol nodes

### CODE REVIEW

**Review by AmrNJ — CHANGES_REQUESTED** [review]
While running the test, I get "EthernetConnection has no field or method SetChoice" error.

**Comment by kjahed** [comment]
> While running the test, I get "EthernetConnection has no field or method SetChoice" error.

Can you provide a bit more context? The test builds and runs fine for me. This error is related to gosnappi (SetChoice was un-exported in v0.13.7) but the test does not really use OTG. In any case, I did rebase so maybe that will help.

**Review by AmrNJ — APPROVED** [review]
LGTM

**Review by AmrNJ — APPROVED** [review]
LGTM

**Pull request merged**
