### PR TITLE
Remove deviation MissingCPUMfgName

### PR DESCRIPTION
**Pull request by mojiiba**
Remove deviation MissingCPUMfgName.

### CODE REVIEW

**Review by guoshiuan — APPROVED** [review]
b/280493291 has the internal test result.

**Review by guoshiuan — COMMENTED** [review]
Please also revise the OTG version of this test: feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go

**Comment by mojiiba** [comment]
> Please also revise the OTG version of this test: feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go

thanks, done

**Review by guoshiuan — APPROVED** [review]

**Pull request merged**
