### PR TITLE
GNMI-1.11: Removing subinterface_packet_counters_missing deviation for Nokia

### PR DESCRIPTION
**Pull request by trathod1**
Removing `subinterface_packet_counters_missing` deviation for Nokia

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Review by NishaSadhasivam-work — CHANGES_REQUESTED** [review]
I see that the subinterface counter path is not present.

Get IsPresent status for path "/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts": got false, want true

Software version: 53987-g34652c2126

Can you please let me know whey we are removing subinterface_packet_counters_missing from the deviation

**Comment by trathod1** [comment]
Subinterface packet counters are supported, however sometimes these counters taking time to get updated just after the subinterface is configured. This was causing the intermittent failure which was observed in your run.

I have committed the fix in the script to perform `gnmi.watch` for the counter, so we have consistent results.

**Review by NishaSadhasivam-work — CHANGES_REQUESTED** [review]
I am seeing the below failure, even with gnmi.watch.

Get IsPresent status for path "/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts": got false, want true
Got path/value: /[interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts:0](https://cs.corp.google.com/piper///depot/google3/interfaces/interface/subinterfaces/subinterface/ipv4/state/counters/in-pkts?ws=nsadhasivam/198&snapshot=11)

Can you please share the expected time delay after configuration for the subinterface leaves to get updated?

**Comment by trathod1** [comment]
Mostly the subinterface counters gets updated immediately, however sometimes it take few seconds. Max I observed was 10 seconds, based on that gnmi.watch was set to 15 seconds to have buffer.

But I am seeing another issue in the counter update, and I am following up with the team here. Let me get back to you after hearing from them.

**Comment by trathod1** [comment]
I have reverted the `gnmi.watch` changes.  Earlier, this particular counter was sensitive to traffic, due to which it was taking time to get updated sometimes. This issue is resolved. Will move PR once image to validate is released.

**Comment by trathod1** [comment]
This would work fine now on latest image.

**Review by NishaSadhasivam-work — APPROVED** [review]
LGTM!

**Pull request merged**
