### PR TITLE
gNMI-1.11: Adding a new deviation for IPv6 discarded packet stats support

### PR DESCRIPTION
**Pull request by sgirishj**
Adding a new deviation for IPv6 discarded packet stats support, to skip verification of below leaves:
/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/in-discarded-pkts
/interfaces/interface/subinterfaces/subinterface/ipv6/state/counters/out-discarded-pkts

### CODE REVIEW

**Review by sachendras — DISMISSED** [review]

**Review by greg-dennis — APPROVED** [review]
Approving Go quality only

**Review by greg-dennis — APPROVED** [review]
Re-approving for Go quality

**Review by rszarecki — DISMISSED** [review]

**Review by sachendras — APPROVED** [review]

**Pull request merged**
