### PR TITLE
TE3.3 hierarchical_weight_resolution_test.go 

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

Increasing traffic flows to 2k from 1k. 

Thanks,
Prabha

### CODE REVIEW

**Comment by LimeHat** [comment]
Could you describe the reasoning for other changes in your PR (besides increasing the flow num.)?

Thanks,

**Comment by cprabha** [comment]
> Could you describe the reasoning for other changes in your PR (besides increasing the flow num.)?
> 
> Thanks,

@LimeHat other changes already approved via https://github.com/openconfig/featureprofiles/pull/1070, I have taken copy  from this pull request.

**Review by greg-dennis — APPROVED** [review]
Approved for Go quality only

**Pull request merged**
