### PR TITLE
TE -13.1 /13.2 - Remove deviation

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

This PR is created for the below changes.

1.) Removed deviation flag from TE-13.1 and TE13.2
2.) Added logf instead of fatalf during concurrent switchover/gribi route add. Since error is expected sometimes if switchover is triggered before all routes are added.

Thanks,
Prabha

### CODE REVIEW

**Review by sachendras — DISMISSED** [review]

**Review by greg-dennis — APPROVED** [review]
Approving for Go quality only

**Review by jasdeep-hundal — APPROVED** [review]

**Pull request merged**
