### PR TITLE
TE-5.1: gRIBI Get RPC

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

Network instance type is set to "DEFAULT".
It is mandatory for user to specify type of network instance. For DEFAULT network instance type is "DEFAULT"

Thanks,
Prabha

### CODE REVIEW

**Comment by sachendras** [comment]
LGTM from me!

@vcheny @vosipchu @xw-g can you please check and approve this PR?.. It is similar to the already merged https://github.com/openconfig/featureprofiles/pull/624

**Comment by vosipchu** [comment]
LGTM

**Review by vosipchu — APPROVED** [review]

**Comment by cprabha** [comment]
Resolved conflicts.

**Comment by sachendras** [comment]
lgtm

**Review by shidzhan — APPROVED** [review]

**Review by sachendras — APPROVED** [review]

**Pull request merged**
