### PR TITLE
OTG Test - RT-5.3: Aggregate Balancing

### LINKED ISSUE #559: OTG: RT-5.3: Aggregate Balancing
- [README](https://github.com/openconfig/featureprofiles/blob/main/feature/interface/aggregate/otg_tests/balancing_test/README.md)

### PR DESCRIPTION
**Pull request by octpetre**
The OTG on KNE conversion for **_RT-5.3: Aggregate Balancing_**
The PR includes the changes from otgutils internal package raised here #514 
IPv6 flow label is not yet supported in OTG....to be added later
Test log output found [here](https://drive.google.com/file/d/1xexg-Ce4avXREmh688PyqOausjxTrWL3/view?usp=sharing)
Fixes #559

### CODE REVIEW

**Comment by alexmasi** [comment]
Please assign this to me for go readability review if deemed appropriate, unfortunately I cannot review this for content

Following the new procedure from https://github.com/openconfig/featureprofiles/pull/606

**Comment by dplore** [comment]
Hi, we'll try Marcus for review of content here.  Thanks!

**Comment by octpetre** [comment]
Hi @marcushines. Could you please review this PR?
Thanks!

**Review by marcushines — APPROVED** [review]

**Comment by octpetre** [comment]
Hi @liulk. Could you please merge?

**Comment by dplore** [comment]
@octpetre merged for you

**Pull request merged**
