### PR TITLE
Update model to ixr10e

### PR DESCRIPTION
**Pull request by cfernanz**

### CODE REVIEW

**Comment by MarcCharlebois** [comment]
@cfernanz should that be done for all textprotos?

**Comment by alexmasi** [comment]
> @cfernanz should that be done for all textprotos? edit: cc @alexmasi

Yes it should be done for all protos assuming ixr10e is the intended FP test compliant model from Nokia. If ixr10 passes some FP tests and ixr10e passes others then there needs to be a larger discussion here.

**Comment by LimeHat** [comment]
>assuming ixr10e is the intended FP test compliant model from Nokia.

yes, that's correct

**Comment by cfernanz** [comment]
Thanks Marc, Alex and Sergey!

updated model to ixr10e for all textproto

**Comment by alexmasi** [comment]
@cfernanz some of the files have 2 DUTs and thus need two lines changed to the new model name

**Comment by cfernanz** [comment]
Thanks Alex. Updated textproto with 2 duts

**Review by alexmasi — APPROVED** [review]

**Pull request merged**
