### PR TITLE
[TE-11.21, TE-3.1, TE-3.7, TE-11.31, TE-3.31] Adding deviations for new subtest for PolicyW

### PR DESCRIPTION
**Pull request by arvbaska1**
Adding deviations for new test/subtest for PolicyW for TE-11.21, TE-3.1, TE-3.7, TE-11.31, TE-3.31 tests

### CODE REVIEW

**Review by AmrNJ — CHANGES_REQUESTED** [review]
Adding too many deviation flags is not a good Go language practice. Please can we minimize those?

**Comment by AmrNJ** [comment]
@arvbaska1 Please can you resolve the conflicts.

**Comment by arvbaska1** [comment]
> @arvbaska1 Please can you resolve the conflicts.

sure, so i see the changes in test TE-11.2,TE-11.3,TE-3.3 have been reverted, and they are now added as new tests.
Will make changes in this PR accordingly.

**Comment by AmrNJ** [comment]
@arvbaska1 LGTM, Please can you resolve conflicts to merge?

**Comment by arvbaska1** [comment]
> @arvbaska1 LGTM, Please can you resolve conflicts to merge?

Sure, i have resolved the conflicts, but the static check has been failing with _no space left on device (compile)_ error for couple days,  do you know if this a CI/CD infra issue ?

https://github.com/openconfig/featureprofiles/actions/runs/8198904891/job/22423170775?pr=2648#step:14:9

**Review by AmrNJ — APPROVED** [review]
LGTM

**Pull request merged**
