### PR TITLE
Initial featureprofile for gNMI's `Get` RPC

### PR DESCRIPTION
**Pull request by robshakir**
```
    Initial (basic) test for gNMI Get RPC.
    
     * (M) proto/feature.proto
        - Add support for specifying a method of the gNMI protocol that
          coverage is being implemented for.
     * (M) feature/system/gnmi/feature.textproto
        - Add feature profile for basic gNMI.
     * (M) feature/system/gnmi/get/...
        - Add feature profile for gNMI Get.
        - Add initial functional tests for gNMI Get against the root.
```

### CODE REVIEW

**Comment by robshakir** [comment]
Note that this fails currently, but is added in as a check to discuss a possible difference in spec interpretation.

**Comment by robshakir** [comment]
This test doesn't pass against the existing targets today, but I'd like to check it in anyway. PTAL.

there's some discussion on the gNMI design for `Get`, I propose to update the test once we've figured that out, since this encodes our current expectations.

**Review by bstoll — APPROVED** [review]

**Review by sthesayi — APPROVED** [review]

**Comment by robshakir** [comment]
Thanks folks -- merging this in. I'm going to start a few `Subscribe` tests too to give a basis for things that we're discovering need to be tested.

**Comment by liulk** [comment]
Resolved #1367

**Pull request merged**
