### PR TITLE
Apply GNOISubcomponentPath deviation to the related tests

### PR DESCRIPTION
**Pull request by mojiiba**
This patch applies  GNOISubcomponentPath to the related tests that use gnoi system APIs. Motivation for GNOISubcomponentPath is discussed in the previous pull https://github.com/openconfig/featureprofiles/pull/717.

### CODE REVIEW

**Comment by mojiiba** [comment]
@sezhang2 could u please review this pr?

**Review by sezhang2 — DISMISSED** [review]

**Review by sezhang2 — DISMISSED** [review]

**Comment by mojiiba** [comment]
@sezhang2 can u please merge this pr?

**Comment by sezhang2** [comment]
> 

Looks like you requested the review from vosipchu. I can help merge after vosipchu approves this PR.

**Comment by mojiiba** [comment]
I intended to add him as assignee, but added as reviewer by mistake. anyway we can wait for his approval. @vosipchu  can u please let me know if u are ok merging this pr?

**Review by thesrinath — APPROVED** [review]

**Review by thesrinath — APPROVED** [review]

**Pull request merged**
