### PR TITLE
P4RT-7.2 PacketOut

### LINKED ISSUE #79: P4RT-7.2: LLDP PacketOut

### PR DESCRIPTION
**Pull request by mingyangcisco**
Resolves #79 This is the PR for P4RT-7.2 LLDP PacketOut. I have made similar changes based on comments in other PacketOut PR.

### CODE REVIEW

**Comment by mingyangcisco** [comment]
Hi @hariramnat, this is the LLDP packet out testcase. I have applied similar changes based on GDP Packetout testcase. When you have time, could you please help check this PR?

**Comment by hariramnat** [comment]
Hey Mingyang, 

Could you upload logs here as well thereby validating your testRun?

**Comment by mingyangcisco** [comment]
> Hey Mingyang,
> 
> Could you upload logs here as well thereby validating your testRun?

Hi @hariramnat , sure. following is the logs of this LLDP PacketOut testcase. Based on the test plan, I removed the sub test for follower packet out. 

`*** Reserving the testbed...


********************************************************************************

  Testbed Reservation Complete
  ID: STATIC

    dut:              DUT
    port1:            HundredGigE0/1/0/20
    port2:            HundredGigE0/1/0/24
    ate:              10.194.88.185
    port1:            6/3
    port2:            6/4

********************************************************************************

=== RUN   TestPacketOut
    lldp_packetout_test.go:243: 
        *** Pushing topology to 10.194.88.185...
        
        
    lldp_packetout_test.go:243: 
        *** Starting protocols on 10.194.88.185...
        
        
    lldp_packetout_test.go:250: 
        *** Creating P4RT client for DUT...
        
        
    lldp_packetout_test.go:255: 
        *** Creating P4RT client for DUT...
        
        
    packetout_test.go:62: Disable LLDP config
=== RUN   TestPacketOut/PacketOut_from_Primary_Controller
    packetout_test.go:93: Received 101 packets on ATE port 6/3
--- PASS: TestPacketOut (168.80s)
    --- PASS: TestPacketOut/PacketOut_from_Primary_Controller (60.28s)
PASS`

**Comment by dplore** [comment]
@mingyangcisco there are conflicts detected.  This is due to other PR's which have merged and updated these files.  Can you rebase / fast forward your pull request to the latest?

**Comment by mingyangcisco** [comment]
> @mingyangcisco there are conflicts detected. This is due to other PR's which have merged and updated these files. Can you rebase / fast forward your pull request to the latest?

yeah. sure. thanks for the reminder. I merged that latest main and resolved the go.mod conflict. I also did a minor change to move the lldp config removal to different location.The changes are done and pushed now.  Following is the latest run logs. 

```
=== RUN   TestPacketOut
    lldp_packetout_test.go:243: 
        *** Pushing topology to 10.194.88.185...
        
        
    lldp_packetout_test.go:243: 
        *** Starting protocols on 10.194.88.185...
        
        
    lldp_packetout_test.go:249: Disable LLDP config
    lldp_packetout_test.go:253: 
        *** Creating P4RT client for DUT...
        
        
    lldp_packetout_test.go:258: 
        *** Creating P4RT client for DUT...
        
        
=== RUN   TestPacketOut/PacketOut_from_Primary_Controller
    packetout_test.go:89: Received 100 packets on ATE port 6/3
--- PASS: TestPacketOut (166.24s)
    --- PASS: TestPacketOut/PacketOut_from_Primary_Controller (61.11s)
PASS
```

**Comment by rsindhujha** [comment]
hi @mingyangcisco ,

Have you explored the LLDP PDU creation with the layers package here? 
https://github.com/google/gopacket/blob/32ee38206866f44a74a6033ec26aeeb474506804/layers/lldp.go

**Comment by mingyangcisco** [comment]
> hi @mingyangcisco ,
> 
> Have you explored the LLDP PDU creation with the layers package here? https://github.com/google/gopacket/blob/32ee38206866f44a74a6033ec26aeeb474506804/layers/lldp.go

@rsindhujha not yet. I will check to see how to use it and add this this testcase.

**Comment by mingyangcisco** [comment]
@rsindhujha I explored layers.lldp in gopacket and used it to generate properly LLDP payload. The changes are done and pushed.

**Review by hariramnat — APPROVED** [review]

**Comment by rsindhujha** [comment]
> @rsindhujha I explored layers.lldp in gopacket and used it to generate properly LLDP payload. The changes are done and pushed.

Thanks @mingyangcisco .

**Pull request merged**
