### PR TITLE
Route installation test fix

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

I have created this pull request to merger changes to configure network instance before configuring bgp in the test "route_installation_test.go" under bgp/policybase.

Path of the script: /root/GitMount/featureprofiles/feature/bgp/policybase/ate_tests/route_installation_test/route_installation_test.go

Ref issue: https://github.com/openconfig/featureprofiles/issues/191

Thanks,
Prabha

### CODE REVIEW

**Comment by cprabha** [comment]
Hi Likai,

We need to configure network instance type, router id for network instance.
I have updated code for network instance type and router id (loopback interface configuration and getting primary ip on loopback interface) .  
Please could you review and approve it.

Thanks,
Prabha

**Comment by liulk** [comment]
Which test plan is this for? RT-1.2 is already done and published here: https://github.com/openconfig/featureprofiles/tree/main/feature/bgp/policybase/ate_tests/route_installation_test

Also, could you please revert the binding and testbed changes?

**Comment by cprabha** [comment]
Hi Likai,

Sure, I will update and commit changes.

Thanks,
Prabha

**Comment by cprabha** [comment]
Hi,

I am opening new pull request after fixing with above comments.
Thank you for the suggestions.

Thanks,
Prabha

**Pull request closed without merging**
