### PR TITLE
fix for gribi test

### PR DESCRIPTION
**Pull request by DanG100**

### CODE REVIEW

**Comment by Ankur19** [comment]
Closing #839 in favour of this.

**Comment by xw-g** [comment]
@DanG100 can you help provide some summary about the context/motivation of this PR? (fix something that was fixed other places but missed this file?)

Seems like this is more about OTG API instead of gRIBI? If so, maybe @bstoll and @liulk has more context as the reviewers? Thanks.

**Review by Ankur19 — APPROVED** [review]
LGTM!

**Comment by Ankur19** [comment]
This is just a library change from ondatra/telemetry to ondatra/gnmi

**Pull request merged**
