### PR TITLE
RT-1.51: BGP multipath ECMP and RT-1.52 bgp_multipath_wecmp_test.go : Added deviation 

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

bgp_multipath_ecmp_test.go
    1. I have updated with deviation for max paths.
    2. Current script is with one source and one destination. I have updated the destination with all advertised routes and added multiple source to verify load balance.

bgp_multipath_wecmp_test.go  
   1. bgp4PeerRoute.ExtendedCommunities().Add() is missing in configure OTG, it will lead to panic failure. 
   2. In traffic flow creation,  port1 used as rx port,  fixed this to start setting rx from port2.

Thanks
Prabha

### CODE REVIEW

**Review by sezhang2 — DISMISSED** [review]
New deviation  _bool bgp_max_multipath_paths_unsupported_ is added for Juniper and tracked by b/319301559

**Review by ram-mac — COMMENTED** [review]
Can we fix the Readme. Have run the tests Rt-1.51 and 1.52 and it passes. So once we have the readme passed we can merge it.

**Comment by cprabha** [comment]
> Can we fix the Readme. Have run the tests Rt-1.51 and 1.52 and it passes. So once we have the readme passed we can merge it.

Sure, will update README.

**Review by ram-mac — APPROVED** [review]
Validated; Looks good now

**Pull request merged**
