### PR TITLE
Default base configs needed for cptx

### PR DESCRIPTION
**Pull request by stthummuri**
Added the default base configs for cptx

### CODE REVIEW

**Comment by alexmasi** [comment]
Tested this with RT-3.1 and test is still failing, full logs here: https://docs.google.com/document/d/1yfSeIRookCBN3nQT7K5uwFEPP2RoJWyhypmKRSM8Khs/edit?usp=sharing @stthummuri

**Comment by stthummuri** [comment]
> Tested this with RT-3.1 and test is still failing, full logs here: https://docs.google.com/document/d/1yfSeIRookCBN3nQT7K5uwFEPP2RoJWyhypmKRSM8Khs/edit?usp=sharing @stthummuri

RT-3.1 has a known failure for our run too. Can you please try the below tests which are dependent on these configs
TE-3.5: Ordering: ACK Received
TE-3.6: ACK in the Presence of Other Routes
TE-4.1: Base Leader Election,
TE-4.2: Leader over
TE-5.1: gRIBI Get RPC
TE-13.2: gRIBI route DELETE during over
TE-14.1: gRIBI Scaling
TE-15.1: gRIBI Compliance

**Comment by alexmasi** [comment]
I tested with te-5.1 and it worked, thanks

**Review by alexmasi — APPROVED** [review]

**Comment by alexmasi** [comment]
@stthummuri Please sync the branch and I will merge

**Pull request merged**
