### PR TITLE
gNMI-1.4:Removed TestSoftwareModule test and deviation_components_software_module_unsupported

### PR DESCRIPTION
**Pull request by mohanasm**
Removed TestSoftwareModule test and deviation 'deviation_components_software_module_unsupported' as discussed in b/277134501.

### CODE REVIEW

**Review by greg-dennis — CHANGES_REQUESTED** [review]
Please resolve merge conflcts

**Comment by mohanasm** [comment]
> Please resolve merge conflcts

Resolved the conflicts. Please check.

**Review by greg-dennis — CHANGES_REQUESTED** [review]
Since it is no longer used, please remove the field from the proto entirely: https://github.com/openconfig/featureprofiles/blob/6b3cfbc39a7fb8fb6a0074c87271560a74de0666/proto/metadata.proto#L183

**Comment by greg-dennis** [comment]
Sorry, I missed that the deviation is used by Arista. Please revert the change to metadata.proto. By bad

**Comment by mohanasm** [comment]
> Sorry, I missed that the deviation is used by Arista. Please revert the change to metadata.proto. By bad

Reverted the changes in metadata.textproto. Please check.

**Comment by sachendras** [comment]
Alternate to `/components/component/software-module/state/module-type` is `/system/state/software-version/` and the same is covered under gNMI-1.10

**Comment by mohanasm** [comment]
> > Sorry, I missed that the deviation is used by Arista. Please revert the change to metadata.proto. By bad
> 
> Reverted the changes in metadata.proto. Please check.

Removed the deviation in deviations.go, metadata.proto, metadata.textproto for all as the testcase using the deviation is removed.

**Review by greg-dennis — APPROVED** [review]

**Pull request merged**
