### PR TITLE
TE 3.3 hierarchical_weight_resolution_test - Increasing Traffic Flows.

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

This pull request is created to increase traffic flows from 256 to 1022.

Thanks,
Prabha

### CODE REVIEW

**Comment by cprabha** [comment]
> What is the reasoning for using 1022 instead of 1024?
Thought of excluding prefix and broadcast address, but we can send traffic to them as well.
I have updated script to use 1024 now.

**Review by greg-dennis — APPROVED** [review]
approving Go quality only

**Review by sachendras — APPROVED** [review]

**Pull request merged**
