### PR TITLE
Update Cloud Build to use prebuilt KNE image

### PR DESCRIPTION
**Pull request by bstoll**

### CODE REVIEW

**Comment by sezhang2** [comment]
featureprofiles-pr check failed. Rerun it.

**Review by sezhang2 — COMMENTED** [review]
featureprofiles-pr check failed. Rerun it.

**Review by sezhang2 — DISMISSED** [review]
Approve it as this PR is to update cloud build.

**Comment by bstoll** [comment]
Forgot to add a note: this isn't ready yet.  The quickest way to test CI changes is to create a PR.  This is still a work-in-progress (marked as a draft).

**Comment by bstoll** [comment]
This is superseded by #1226

**Pull request closed without merging**
