### PR TITLE
gNMI-1.15: gnmi_set_test.go : Added deviation

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

1. Setting config.Interface = nil when no interfaces are attached to config.
2. Checking for null value for state telemetry
3. Added deviation for static protocol index check 

Thanks,
Prabha

### CODE REVIEW

**Review by sezhang2 — APPROVED** [review]
The PR introduced a new deviation **SkipStaticNexthopCheck** for Juniper only.

Please open a bug to track why we need this new flag and when this deviation flag will be removed.

**Comment by sezhang2** [comment]
Please resolve conflicts.

**Review by sezhang2 — APPROVED** [review]
Re-approve the code after the conflict is resolved.

**Comment by sezhang2** [comment]
Please resolve conflicts.

**Comment by cprabha** [comment]
> Please resolve conflicts.

Resolved conflicts, please check.

**Review by sezhang2 — APPROVED** [review]
Need to verify the test results before merge.

**Review by sezhang2 — COMMENTED** [review]
Please resolve conflicts.

**Review by sezhang2 — APPROVED** [review]

**Review by arulkumarsekar — DISMISSED** [review]
re-approving

**Review by arulkumarsekar — APPROVED** [review]
re-approving

**Pull request merged**
