### PR TITLE
NI Deviation requiring testing.TB interface reference update.

### PR DESCRIPTION
**Pull request by trathod1**
Followup changes based on - https://github.com/openconfig/featureprofiles/pull/939#discussion_r1062924708

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by xw-g** [comment]
@liulk I'm not familiar with our choice of T and TB, maybe you can help offer some opinions?

BTW: the usage of the deviation is approved and Quattro team is ok with it.

**Review by liulk — CHANGES_REQUESTED** [review]
Can we change fptest.AssignToNetworkInstance to just take testing.TB, not *testing.T? Also if not already, make sure it calls t.Helper() the first thing.

**Comment by liulk** [comment]
To provide some rationale: *testing.T can be converted to a testing.TB but not vice versa, so helpers in a shared package should only accept testing.TB. This is to avoid having large scale changes like this PR.

**Comment by trathod1** [comment]
> Can we change fptest.AssignToNetworkInstance to just take testing.TB, not *testing.T? Also if not already, make sure it calls t.Helper() the first thing.

Updated deviation as per comment. Restored testing.TB argument in session.go and setup_test.go as before.
I understand, these changes would be applicable to [`fptest.SetPortSpeed` ](https://github.com/nokia/featureprofiles/blob/99ea33270e5e6d3ca3e97278605413ac40ef5740/internal/fptest/portspeed.go#L44)deviation also. Will update it in separate PR.

**Comment by trathod1** [comment]
@liulk Does this look fine ? Will raise a PR with similar changes for fptest.SetPortSpeed based on it.

**Comment by xw-g** [comment]
The deviation usage is LGTMed, waiting for @liulk to LGTM the TB changes.

**Review by liulk — APPROVED** [review]

**Pull request merged**
