### PR TITLE
TE-15.1: Adding flag to skip ipv6 compliance cases

### PR DESCRIPTION
**Pull request by trathod1**
Based on discussion in b/318469590 making following changes -
    1. Adding `skip_ipv6` flag to skip recently added ipv6 tests in gribigo compliance library.
    2. Updating `gribigo` package version in `go.mod`

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by LimeHat** [comment]
@greg-dennis, can you please help to solve the static analysis issue here?
```
go: github.com/mgechev/revive@latest (in github.com/mgechev/revive@v1.3.5):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
Error: Process completed with exit code 1.
```
It doesn't seem to be directly related to the changes in this PR, we're only bumping gribigo version in go.mod

**Review by NishaSadhasivam-work — APPROVED** [review]
LGTM!

**Comment by LimeHat** [comment]
> @greg-dennis, can you please help to solve the static analysis issue here?
> Perhaps caused by a new revive release [published earlier today](https://github.com/mgechev/revive/releases/tag/v1.3.5)?

yep the static check error is from an upstream repo: https://github.com/mgechev/revive/issues/956#issuecomment-1876731280

**Comment by LimeHat** [comment]
@NishaSadhasivam-work static check issue was resolved

thanks!

**Pull request merged**
