### PR TITLE
OTG Test - DP-1.4: QoS Interface Output Queue Counters

### LINKED ISSUE #796: OTG: dp-1.4: QoS Interface Output Queue Counters

### PR DESCRIPTION
**Pull request by ANISH-GOTTAPU**
OTG conversion of DP-1.4: QoS Interface Output Queue Counters
Fixes #796 
Output log [here](https://drive.google.com/file/d/17ujGxbMEa3McwWTpzvsIvCsuHQNtD4uF/view?usp=share_link)

### CODE REVIEW

**Comment by sezhang2** [comment]
This is an experimental code with default qos policy config.

I am going to add several QoS traffic tests to cover the strict priority and WRR. The queue counters will be checked in each test.

**Review by sezhang2 — APPROVED** [review]

**Comment by sezhang2** [comment]
I will merge this experimental PR.

Please note, new test will replace this one

**Comment by ANISH-GOTTAPU** [comment]
> I will merge this experimental PR.
> 
> Please note, new test will replace this one

sure thanks. noted

**Pull request merged**
