### PR TITLE
updated string to int

### PR DESCRIPTION
**Pull request by Hobbydos**
marshall string to int

### CODE REVIEW

**Comment by Hobbydos** [comment]
cc @robshakir  @xw-g

**Review by robshakir — APPROVED** [review]
This looks consistent with other changes agreed publicly. @xw-g PTAL and merge if you're OK with this.

**Comment by xw-g** [comment]
@vcheny @sachendras @vosipchu  Because this is implementing agreed upon OC clarification: https://github.com/openconfig/public/pull/732, I'm going to merge this PR with just LGTM from @robshakir and I.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
