### PR TITLE
 RT-1.28: Fixed script with added deviations 

### PR DESCRIPTION
**Pull request by snaragund**
- Added new deviation EnableTableConnections & other required deviation. 
 - Used `bgp_community_member_is_a_string: true` with reference to https://partnerissuetracker.corp.google.com/issues/376799780#comment2 
 - Match-Community-Set under bgp-conditions configuration moved to policy-defitions as its configuration is deprecated under bgp-defined-sets. 
 - Under nonMatchingCommunityRoutePolicy(both v4 & v6) changed gnmi.Replace to gnmi.Update to avoid precondition error of failing to delete AllowAll route-policy.
 

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by snaragund** [comment]
After https://github.com/openconfig/featureprofiles/pull/3359 is resolved will commit changes & share logs.

**Comment by dplore** [comment]
@snaragund this is missing the [InterfaceEnabled deviation](https://github.com/openconfig/featureprofiles/blob/2c90d9f5e6e648aec27e7c1816e31a4fe1f285ce/internal/deviations/deviations.go#L270) which srlinux requires.  

I see the deviation is enabled in the metadata.textproto for this test, but there is no code in the isis sessions package to use it.   You'll need to update that to get this test to pass.

Ref: https://github.com/openconfig/featureprofiles/blob/2c90d9f5e6e648aec27e7c1816e31a4fe1f285ce/internal/isissession/isissession.go#L203

**Review by dplore — CHANGES_REQUESTED** [review]
Please add InterfaceEnabled as required for srlinux where necessary (I think it's just in the isissessions package)

**Comment by snaragund** [comment]
@dplore please do check logs ConfigOCInterface in attrs package & then in isissession package. It has respective bgp_isis_redistribution_test.go, isissession.go, attrs.go files to refer. In both ways tests are passing.

https://partnerissuetracker.corp.google.com/issues/382020665

**Comment by dplore** [comment]
> @dplore please do check logs when ConfigOCInterface called in attrs package & then in isissession package. It has respective bgp_isis_redistribution_test.go, isissession.go, attrs.go files to refer. In both ways tests are passing.
> 
> https://partnerissuetracker.corp.google.com/issues/382020665#comment3

Got it.  It turned out I was running the wrong code.  Also I have run into a bug in OTG in our environment which is now fixed.  I  now have the test passing in my environment and will complete the review on Monday next week.

**Review by dplore — APPROVED** [review]

**Comment by dplore** [comment]
@openconfig/featureprofiles-approvers this is ready for final review/approval

**Review by dplore — DISMISSED** [review]

**Review by self-maurya — DISMISSED** [review]

**Review by dplore — APPROVED** [review]

**Comment by dplore** [comment]
@self-maurya for final approval

**Review by self-maurya — APPROVED** [review]

**Pull request merged**
