### PR TITLE
Remove deviation gnoi_fabric_component_reboot_unsupported

### PR DESCRIPTION
**Pull request by nicjiang2023**
Remove deviation gnoi_fabric_component_reboot_unsupported for Juniper in metadata.textproto

### CODE REVIEW

**Review by sachendras — APPROVED** [review]

**Review by greg-dennis — APPROVED** [review]
Approving for Go quality

**Comment by sachendras** [comment]
Since this test is looking for the existence of removable fabric/linecards and would fail if none exists, FFF chassis w/o removable fabric cards and Linecards will always fail this test. Hence please skip the tests [for removable fabric](https://github.com/openconfig/featureprofiles/blob/main/feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go#L244) and for [removable line cards](https://github.com/openconfig/featureprofiles/blob/main/feature/gnoi/system/tests/per_component_reboot_test/per_component_reboot_test.go#L173) if the boolean /components/component/state/removable == TRUE.

**Review by sachendras — APPROVED** [review]

**Comment by nicjiang2023** [comment]
To resolve conflicts issue, close current pull request.

It will be tracked via new pull request:
https://github.com/openconfig/featureprofiles/pull/2232

**Pull request closed without merging**
