### PR TITLE
RT-7 : bgp_default_policies_test.go 

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

I have change gnmi.replace to gnmi.update while configuring loopback interface.

Thanks,
Prabha

### CODE REVIEW

**Comment by sezhang2** [comment]
Hi,

Can you check both replace and update operates as expected by printing out all the set values in the following code?

```
// Update updates the configuration at the given query path with the val.
func Update[T any](ctx context.Context, c *Client, q ConfigQuery[T], val T, opts ...Option) (*Result, error) {
	resp, path, err := set(ctx, c, q, val, updatePath, opts...)
	if err != nil {
		return nil, fmt.Errorf("Update(t) at path %s: %w", path, err)
	}
	return responseToResult(resp), nil
}

// Replace replaces the configuration at the given query path with the val.
func Replace[T any](ctx context.Context, c *Client, q ConfigQuery[T], val T, opts ...Option) (*Result, error) {
	resp, path, err := set(ctx, c, q, val, replacePath, opts...)
	if err != nil {
		return nil, fmt.Errorf("Replace(t) at path %s: %w", path, err)
	}
	return responseToResult(resp), nil
}
```

**Comment by LimeHat** [comment]
While this should work to avoid the removal of non-zero indexed subinterfaces, I don't believe this is the correct approach: lo0.0 can also be used for infra purposes in some setups, and this will override the existing lo0.0 IP addressing.

I have another proposal in #2498 that both
1) preserves the existing logic for vendors that need it
2) reuses the existing IP info from lo0.0 if it is available

**Comment by cprabha** [comment]
> Hi,
> 
> Can you check if both replace and update operate as expected by printing out all the set values in the following code?
> 
> ```
> // Update updates the configuration at the given query path with the val.
> func Update[T any](ctx context.Context, c *Client, q ConfigQuery[T], val T, opts ...Option) (*Result, error) {
> 	resp, path, err := set(ctx, c, q, val, updatePath, opts...)
> 	if err != nil {
> 		return nil, fmt.Errorf("Update(t) at path %s: %w", path, err)
> 	}
> 	return responseToResult(resp), nil
> }
> 
> // Replace replaces the configuration at the given query path with the val.
> func Replace[T any](ctx context.Context, c *Client, q ConfigQuery[T], val T, opts ...Option) (*Result, error) {
> 	resp, path, err := set(ctx, c, q, val, replacePath, opts...)
> 	if err != nil {
> 		return nil, fmt.Errorf("Replace(t) at path %s: %w", path, err)
> 	}
> 	return responseToResult(resp), nil
> }
> ```

Please check.

Update Function:
===========

Update Function: resp: prefix:{} response:{path:{origin:"openconfig" elem:{name:"interfaces"} elem:{name:"interface" key:{key:"name" value:"lo0"}}} op:UPDATE} timestamp:1702928770547835765
Update Function: path: origin:"openconfig" elem:{name:"interfaces"} elem:{name:"interface" key:{key:"name" value:"lo0"}}
Update Function: q: /interfaces/interface[name=lo0]
Update Function: val: &{out-of-range E_Interface_AdminStatus enum value: 0 %!s(*oc.Interface_Aggregation=<nil>) %!s(*oc.Interface_Counters=<nil>) %!s(*bool=<nil>) %!s(*string=0xc0009d05e0) %!s(*bool=<nil>) %!s(*oc.Interface_Ethernet=&{<nil> <nil> <nil> 0 <nil> 0 <nil> <nil> 0 0 0 <nil> <nil>}) %!s(*bool=<nil>) %!s(*string=<nil>) %!s(*oc.Interface_HoldTime=<nil>) %!s(*uint32=<nil>) %!s(*uint32=<nil>)  %!s(*uint64=<nil>) %!s(*bool=<nil>) out-of-range E_Interfaces_LoopbackModeType enum value: 0 %!s(*bool=<nil>) %!s(*uint16=<nil>) %!s(*string=0xc0009d05a0) out-of-range E_Interface_OperStatus enum value: 0  %!s(*oc.Interface_PenaltyBasedAied=<nil>) [] %!s(*oc.Interface_RoutedVlan=<nil>) map[%!s(uint32=0):%!s(*oc.Interface_Subinterface=&{0 <nil> <nil> <nil> <nil> <nil> 0xc002810150 0xc004c30200 0xc003510870 <nil> <nil> <nil> <nil> 0 <nil>})] out-of-range E_VlanTypes_TPID_TYPES enum value: 0 %!s(*string=<nil>) softwareLoopback}


ReplaceFunction :
============
Replace Function: resp: prefix:{}  response:{path:{origin:"openconfig"  elem:{name:"interfaces"}  elem:{name:"interface"  key:{key:"name"  value:"lo0"}}}  op:REPLACE}  timestamp:1702929292016106774
Replace Function: path: origin:"openconfig"  elem:{name:"interfaces"}  elem:{name:"interface"  key:{key:"name"  value:"lo0"}}
Replace Function: q: /interfaces/interface[name=lo0]
Replace Function: val: &{out-of-range E_Interface_AdminStatus enum value: 0 %!s(*oc.Interface_Aggregation=<nil>) %!s(*oc.Interface_Counters=<nil>) %!s(*bool=<nil>) %!s(*string=0xc002401810) %!s(*bool=<nil>) %!s(*oc.Interface_Ethernet=&{<nil> <nil> <nil> 0 <nil> 0 <nil> <nil> 0 0 0 <nil> <nil>}) %!s(*bool=<nil>) %!s(*string=<nil>) %!s(*oc.Interface_HoldTime=<nil>) %!s(*uint32=<nil>) %!s(*uint32=<nil>)  %!s(*uint64=<nil>) %!s(*bool=<nil>) out-of-range E_Interfaces_LoopbackModeType enum value: 0 %!s(*bool=<nil>) %!s(*uint16=<nil>) %!s(*string=0xc002401800) out-of-range E_Interface_OperStatus enum value: 0  %!s(*oc.Interface_PenaltyBasedAied=<nil>) [] %!s(*oc.Interface_RoutedVlan=<nil>) map[%!s(uint32=0):%!s(*oc.Interface_Subinterface=&{0 <nil> <nil> <nil> <nil> <nil> 0xc002e96298 0xc0023cb500 0xc001fb5860 <nil> <nil> <nil> <nil> 0 <nil>})] out-of-range E_VlanTypes_TPID_TYPES enum value: 0 %!s(*string=<nil>) softwareLoopback}

**Comment by cprabha** [comment]
> While this should work to avoid the removal of non-zero indexed subinterfaces, I don't believe this is the correct approach: lo0.0 can also be used for infra purposes in some setups, and this will override the existing lo0.0 IP addressing.
> 
> I have another proposal in #2498 that both
> 
> 1. preserves the existing logic for vendors/setups that need it
> 2. reuses the existing IP info from lo0.0 if it is available
> 
> Alternatively, the code should be reworked to create a new loopback interface/subinterface, to avoid possible collisions with the existing configs. This would be an optimal solution. I don't know if all vendors support multiple loopbacks and/or loopback subinterfaces - but if the author is willing to introduce that logic, I'd be in favor of it.

As per README we are adding new IP. Update function will configure new test ip on unit 0 ( DUT:Port2 has IBGP peering with ATE:Port2 using its loopback interface. The loopback interface is reachable only via IS-IS.)

**Comment by LimeHat** [comment]
I don't see a requirement in the README to use lo0.0 (or update that address, for that matter)

If you want to exclusively use a new address for the test loopback, then please add the logic to create a new lo0 subinterface or a new loopback interface that does not override the existing configs

**Comment by cprabha** [comment]
Will go  with https://github.com/openconfig/featureprofiles/pull/2498, and closing this one pull request.

**Pull request closed without merging**
