### PR TITLE
p4rt-6.1: small fixes

### PR DESCRIPTION
**Pull request by LimeHat**
A couple of minor fixes:

1. Fix LLDP & GDP packet counters in PacketIn scenario; previously they counted only frames matched on the second switch case statement [metadata egress port id]
2. Add a short sleep timer (3 s) before ATE stats retrieval for PacketOut test cases

Additionally, removed a few unused parameters and code paths:

1. icmp6 traceroute packet structs (since icmp6 is not used in this case)
2. `submitIngress` bool flag from submitIngress() func (unused)
3. `args` param from newTrafficFlow func (unused)

---
<sup>
This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind.</sup>

### CODE REVIEW

**Review by Ankur19 — DISMISSED** [review]
LGTM!

Sorry I didn't see this before. Hence made another PR with some similar changes. However, not everything is the same: https://github.com/openconfig/featureprofiles/pull/1725

Can we add the GDP and LLDP Packet IN Counting logic and the Sleep before ATE read after merging the other PR?

**Comment by xw-g** [comment]
> LGTM!
> 
> Sorry I didn't see this before. Hence made another PR with some similar changes. However, not everything is the same: #1725
> 
> Can we add the GDP and LLDP Packet IN Counting logic and the Sleep before ATE read after merging the other PR?

@Ankur19 do you mean: 
1. wait your https://github.com/openconfig/featureprofiles/pull/1725 to get merged firs. 
2. make the suggested changes to this PR, and then merge this PR?

**Comment by Ankur19** [comment]
> > LGTM!
> > Sorry I didn't see this before. Hence made another PR with some similar changes. However, not everything is the same: #1725
> > Can we add the GDP and LLDP Packet IN Counting logic and the Sleep before ATE read after merging the other PR?
> 
> @Ankur19 do you mean:
> 
> 1. wait your [Update performance_test.go #1725](https://github.com/openconfig/featureprofiles/pull/1725) to get merged firs.
> 2. make the suggested changes to this PR, and then merge this PR?

Yes.

**Comment by LimeHat** [comment]
Ok I'll wait and rebase the PR.
Thx

**Comment by LimeHat** [comment]
Updated,

@Ankur19, please take another look
Thanks!

**Review by Ankur19 — APPROVED** [review]
LGTM!

**Pull request merged**
