### PR TITLE
gNMI-1.3,RT-1.2,RT-1.3,RT-1.4 | Changes to add RPL under BGP Peer-group AFI without deviation

### PR DESCRIPTION
**Pull request by arvbaska1**
Made below changes to the testcases similar to PR https://github.com/openconfig/featureprofiles/pull/1538 to have RPL under peergroup AFI/SAFI as the defualt.

1) gNMI-1.3
- Changed RPL under AFI in peergroup to be as default , and RPL in peergroup directly with a deviation RoutePolicyUnderAFIUnsupported.
- Removed additional Peer-group, PeerGrpEgressName since existing Peer-group can be used.
- Changed to use MED attribute instead of local preference since https://github.com/openconfig/featureprofiles/issues/759 is addressed.

2) RT-1.2, RT-1.3, RT-1.4
- Changed to RPL under peergroup AFI to be as default, and use deviation RoutePolicyUnderAFIUnsupported to add RPL under peer-group directly.

3) Removed deviation RoutePolicyUnderPeerGroup from deviations.go

### CODE REVIEW

**Comment by xw-g** [comment]
@LimeHat I think the proposal (from the PR description) sounds good to me. Do you give green light? 

You might need a follow up PR to iterate the drain test though.

**Comment by LimeHat** [comment]
Yes looks good, we'll file a PR later 

cc @MarcCharlebois @trathod1

**Review by prinikasn — APPROVED** [review]

**Review by prinikasn — COMMENTED** [review]
/gcbrun

**Comment by prinikasn** [comment]
Test results at b/285230548#comment2 .

OTG check failure here is because '..otg_tests/route_propagation_test/route_propagation_test.go' does not have the `RoutePolicyUnderPeerGroup` deviation

**Review by prinikasn — COMMENTED** [review]
/gcbrun

**Pull request merged**
