### PR TITLE
Add InterfaceType to interface configuration (oc.IETFInterfaces_InterfaceType_ethernetCsmacd)

### PR DESCRIPTION
**Pull request by sgirishj**
Added InterfaceType to interface configuration (oc.IETFInterfaces_InterfaceType_ethernetCsmacd).

Similar changes have been already added to other scripts. One example - https://github.com/openconfig/featureprofiles/pull/1112

### CODE REVIEW

**Review by sachendras — APPROVED** [review]

**Review by greg-dennis — APPROVED** [review]
approving for Go quality only

**Pull request merged**
