### PR TITLE
gNOI-2.1: Reducing MTU size from 9000 to 8148 bytes

### PR DESCRIPTION
**Pull request by yashikakn**
Per discussion in issue 279896696, reducing max MTU size from 9000 to 8148 bytes.

### CODE REVIEW

**Review by sachendras — DISMISSED** [review]

**Review by greg-dennis — DISMISSED** [review]
Approving for Go quality

**Review by sachendras — APPROVED** [review]

**Review by greg-dennis — APPROVED** [review]
Approving for Go quality

**Pull request merged**
