### PR TITLE
gNMI-1.13 : Update interface type  in optics_power_and_bias_current_test.go

### PR DESCRIPTION
**Pull request by adityayennam**
Adding mandatory interface type in configuration

### CODE REVIEW

**Comment by sezhang2** [comment]
Please pick up the latest fix from https://github.com/openconfig/featureprofiles/pull/840 which fixed the static analysis failure.

**Comment by sezhang2** [comment]
Please rebase your code to pick up the latest fix from https://github.com/openconfig/featureprofiles/pull/840 which fixed the static analysis failure.

**Comment by adityayennam** [comment]
Closing the issue. Addressed in https://github.com/openconfig/featureprofiles/pull/860

**Pull request closed without merging**
