### PR TITLE
TE-2.1.1 single_decap_gribi_entry_test.go

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

This is initial commit for TE-2.1.1: Single Decap gRIBI Entry.
For ip addresses as defined in testplan needs https://github.com/openconfig/featureprofiles/pull/2404 to be merged

Thanks,
Prabha

### CODE REVIEW

**Comment by xw-g** [comment]
@cprabha  Can you help link the issue that tracks the requirement/implmentation here? Thanks!

**Comment by sezhang2** [comment]
Can you fix the failed check?

```
Run find . -name \*.go -exec ./tools/check_ip_addresses.pl \{} +

./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:65: 	ipv[4](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:5)OuterDst111       = "192.[5](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:6)1.100.[6](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:7)4"
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:67: 	ipv4OuterDst333       = "192.58.200.7"
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:252: 	// Using gRIBI, install an  IPv4Entry for the prefix 192.51.100.1/24 that points to a
Error: detected usage of IPv4 and IPv6 addresses outside of the
documentation range.  Please see "IP Addresses Assignment" in
CONTRIBUTING.md for detail.

./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:633: 		prefixWithMask: "192.51.100.0/24",
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:636: 		prefixWithMask: "192.51.100.64/32",
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:639: 		prefixWithMask: "192.51.100.64/28",
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:642: 		prefixWithMask: "192.51.100.0/22",
./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:669: 			// Test with packets with a destination address such as 192.58.200.[7](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:8) that does not match
Error: Process completed with exit code 1.
```

**Comment by sezhang2** [comment]
Please also resolve conflicts.

**Comment by cprabha** [comment]
> @cprabha Can you help link the issue that tracks the requirement/implmentation here? Thanks!

@xw-g This test is automated based on DCGate testplan and requires enhancement based on issue/2222.We will check and update it.

**Comment by cprabha** [comment]
> Can you fix the failed check?
> 
> ```
> Run find . -name \*.go -exec ./tools/check_ip_addresses.pl \{} +
> 
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:65: 	ipv[4](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:5)OuterDst111       = "192.[5](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:6)1.100.[6](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:7)4"
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:67: 	ipv4OuterDst333       = "192.58.200.7"
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:252: 	// Using gRIBI, install an  IPv4Entry for the prefix 192.51.100.1/24 that points to a
> Error: detected usage of IPv4 and IPv6 addresses outside of the
> documentation range.  Please see "IP Addresses Assignment" in
> CONTRIBUTING.md for detail.
> 
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:633: 		prefixWithMask: "192.51.100.0/24",
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:636: 		prefixWithMask: "192.51.100.64/32",
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:639: 		prefixWithMask: "192.51.100.64/28",
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:642: 		prefixWithMask: "192.51.100.0/22",
> ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:669: 			// Test with packets with a destination address such as 192.58.200.[7](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:8) that does not match
> Error: Process completed with exit code 1.
> ```

@sezhang2 These ip addresses are explicitly mentioned in dcgate testplan (https://github.com/openconfig/featureprofiles/pull/2217/files).  Please could you add them to CONTRIBUTING.md

**Comment by cprabha** [comment]
> > Can you fix the failed check?
> > ```
> > Run find . -name \*.go -exec ./tools/check_ip_addresses.pl \{} +
> > 
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:65: 	ipv[4](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:5)OuterDst111       = "192.[5](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:6)1.100.[6](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:7)4"
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:67: 	ipv4OuterDst333       = "192.58.200.7"
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:252: 	// Using gRIBI, install an  IPv4Entry for the prefix 192.51.100.1/24 that points to a
> > Error: detected usage of IPv4 and IPv6 addresses outside of the
> > documentation range.  Please see "IP Addresses Assignment" in
> > CONTRIBUTING.md for detail.
> > 
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:633: 		prefixWithMask: "192.51.100.0/24",
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:636: 		prefixWithMask: "192.51.100.64/32",
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:639: 		prefixWithMask: "192.51.100.64/28",
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:642: 		prefixWithMask: "192.51.100.0/22",
> > ./feature/experimental/gribi/otg_tests/single_decap_giribi_entry/single_decap_gribi_entry_test.go:669: 			// Test with packets with a destination address such as 192.58.200.[7](https://github.com/openconfig/featureprofiles/actions/runs/6790615371/job/18460397758?pr=2355#step:4:8) that does not match
> > Error: Process completed with exit code 1.
> > ```
> 
> @sezhang2 These ip addresses are explicitly mentioned in dcgate testplan (https://github.com/openconfig/featureprofiles/pull/2217/files). Please could you add them to CONTRIBUTING.md

@sezhang2  Sure, I will update contributing.MD and move PR back to open state.  Thank you.

**Comment by cprabha** [comment]
Needs https://github.com/openconfig/featureprofiles/pull/2404 to be merged

**Comment by sezhang2** [comment]
> Needs #2404 to be merged

Ack, I added a couple of people to review #2404.

**Comment by cprabha** [comment]
New pull request is opened to address decap testcases.
https://github.com/openconfig/featureprofiles/pull/2519

**Pull request closed without merging**
