### PR TITLE
RT-1.27: Static route to BGP redistribution

### PR DESCRIPTION
**Pull request by trathod1**
Following changes are in this PR -
 1. Adding script `static_route_bgp_redistribuon_test.go`
 2. Following new deviations are added - 
          - `skip_bgp_send_community_type`
          - `use_vendor_native_tag_set_config`
          - `table_connections_unsupported`

“This code is a Contribution to the OpenConfig Feature Profiles project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an “as is” basis without any warranties of any kind.”

### CODE REVIEW

**Comment by trathod1** [comment]
Not able to update the UUID. Probably we need to change this script folder in the repo based on - 
``` 
$ go run ./tools/addrundata --fix
Test found in a bad path: feature/bgp/static_route_bgp_redistribution/static_route_bgp_redistribution_test.go
F0416 17:40:15.705688   43930 main.go:47] Problems found under feature root.  Please make sure test paths follow feature/<feature>/<subfeature>/<testkind>/<testname>/<testname>_test.go and all tests have an accompanying README.md in the test directory.
exit status 1
```

Please suggest.

**Comment by cfernanz** [comment]
> Not able to update the UUID. Probably we need to change this script folder in the repo based on -
> 
> ```
> $ go run ./tools/addrundata --fix
> Test found in a bad path: feature/bgp/static_route_bgp_redistribution/static_route_bgp_redistribution_test.go
> F0416 17:40:15.705688   43930 main.go:47] Problems found under feature root.  Please make sure test paths follow feature/<feature>/<subfeature>/<testkind>/<testname>/<testname>_test.go and all tests have an accompanying README.md in the test directory.
> exit status 1
> ```
> 
> Please suggest.

Let's move the files to below directory,
 - feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/static_route_bgp_redistribution_test.go
 - feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/README.md
 - feature/bgp/static_route_bgp_redistribution/otg_tests/static_route_bgp_redistribution_test/metadata.textproto


Also update https://github.com/openconfig/featureprofiles/blob/129ac0a4eff8a5bfd3bea777ccdb2c5421ccd5e6/testregistry.textproto#L490

**Comment by trathod1** [comment]
Updated paths as per comment.

**Review by cfernanz — APPROVED** [review]
LGTM

**Pull request merged**
