### PR TITLE
DP-1.14: Adding deviation for no zero suppression

### PR DESCRIPTION
**Pull request by charantejag504**
Adding deviation for no zero suppression

1. Sample mode introduced in DP-1.14 requires even zero values to be exported.
2. Removing default zero suppression to support the sample mode validations.

### CODE REVIEW

**Review by sezhang2 — COMMENTED** [review]
Should the PR tile change to **no zero suppression** ?

BTW, the deviation is used for the workaround, but **no zero suppression** is required (not a workaround).

**Comment by sezhang2** [comment]
Please also fix the code:

_Error: feature/qos/otg_tests/qos_basic_test/qos_basic_test.go:1793:9: unnecessary use of fmt.Sprintf (S1039)_

**Comment by charantejag504** [comment]
@sezhang2, updated the PR title.

**Comment by charantejag504** [comment]
Addressed all the comments.

**Pull request merged**
