### PR TITLE
OTG Test - RT-1.19: BGP 2-Byte and 4-Byte ASN support

### LINKED ISSUE #1937: OTG: RT-1.24: BGP 2-Byte and 4-Byte ASN support

### PR DESCRIPTION
**Pull request by octpetre**
OTG version of this test.
Resolves #1937

### CODE REVIEW

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]
@octpetre : Needs a metadata sync, otherwise it's LGTM.

**Comment by octpetre** [comment]
> @octpetre : Needs a metadata sync, otherwise it's LGTM.

Done

**Review by jasdeep-hundal — CHANGES_REQUESTED** [review]
@octpetre : Metadata formatting is still off.

**Comment by octpetre** [comment]
> @octpetre : Metadata formatting is still off.

@jasdeep-hundal I fixed the metadata file

**Review by jasdeep-hundal — APPROVED** [review]

**Pull request merged**
