### PR TITLE
Update qos_output_queue_counters_test.go

### PR DESCRIPTION
**Pull request by saarvind6481**
added deviations for droppedoctects

### CODE REVIEW

**Review by sezhang2 — DISMISSED** [review]
Why is deviation_qos_dropped_octets added? dropped octets is a required feature support for QoS and vendor neutral counter.

**Comment by vosipchu** [comment]
@sezhang2 Sean, that's the purpose, we start with a deviation and when support comes (or we agree it is not a req), we will remove this.

**Comment by sezhang2** [comment]
> @sezhang2 Sean, that's the purpose, we start with a deviation and when support comes (or we agree it is not a req), we will remove this.

SGTM. Is there is a bug to track the drop counter support?

**Review by prinikasn — COMMENTED** [review]
/gcbrun

**Review by prinikasn — APPROVED** [review]

**Pull request merged**
