### PR TITLE
Update RT-5.6 to change link down on port1 instead of all ports

### PR DESCRIPTION
**Pull request by ANISH-GOTTAPU**
Fix for the issue reported https://github.com/open-traffic-generator/fp-testbed-juniper/issues/77

### CODE REVIEW

**Comment by ram-mac** [comment]
@ANISH-GOTTAPU can you fix the failures in the PR approval workflow and raise request for review again?

**Comment by ANISH-GOTTAPU** [comment]
> @ANISH-GOTTAPU can you fix the failures in the PR approval workflow and raise request for review again?

@ram-mac : I am getting this as error, can you help me on how to proceed with this.

Match found: File - /feature/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go, Pattern - /feature/interface/{/**,}
Required codeowners: featureprofiles-maintainers, ram-mac
Required approvals not met: Not all codeowners have approved. and total approvals:0 < minimum approvals:2

**Comment by dplore** [comment]
> > @ANISH-GOTTAPU can you fix the failures in the PR approval workflow and raise request for review again?
> 
> @ram-mac : I am getting this as error, can you help me on how to proceed with this.
> 
> Match found: File - /feature/interface/interface_loopback_aggregate/otg_tests/interface_loopback_aggregate/interface_loopback_aggregate_test.go, Pattern - /feature/interface/{/**,} Required codeowners: featureprofiles-maintainers, ram-mac Required approvals not met: Not all codeowners have approved. and total approvals:0 < minimum approvals:2

This PR needs two approvers (currently has none).  

One approver needs to be the [codeowner for feature/interface](https://github.com/openconfig/featureprofiles/blob/main/.github/CODEOWNERS#L20) which is @ram-mac.  After he has approved, a reviewer from [featureprofiles-approvers](https://github.com/orgs/openconfig/teams/featureprofiles-approvers) must also approve.  Then the PR can be merged.

**Review by ram-mac — APPROVED** [review]
LGTM

**Review by dplore — APPROVED** [review]

**Pull request merged**
