### PR TITLE
policy based vrf selection - RT3.1 protocol dscp based vrf selection

### PR DESCRIPTION
**Pull request by singh-prem**
### testcase to cover RT3.1 in policy based vrf selection.
- Added test RT3.1 with DSCP, IPv4, IPv6, IPinIP based VRF selection covering 5 subcases:
1. Matching ipv4 protocol to VRF10. Dropping IPv6 traffic in VRF10
2. Matching IPv4 protocol to VRF10, IPv6 protocol to VRF20. Dropping IPv6 traffic in VRF10 and IPv4 in VRF20.
3. Match IPinIP protocol to VRF10. Drop IPv4 and IPv6 traffic in VRF10.
4. Match IPinIP and single DSCP46 to VRF10. Drop DSCP0 in VRF10.
5. Match IPinIP and single DSCP46, DSCP42 to VRF10. Drop DSCP0 in VRF10.

[logs.txt](https://github.com/openconfig/featureprofiles/files/8838888/logs.txt)

### CODE REVIEW

**Comment by dplore** [comment]
/gcbrun to see if it fixes featureprofiles-pr CI check

**Comment by singh-prem** [comment]
@dplore kindly suggest next steps. Is there anything pending on from author?

**Comment by xw-g** [comment]
@dplore is OOO. Next step is code review, right? @liulk 

@liulk I can help review the README, let me know. Thanks.

**Comment by smulky** [comment]
PR for same under #228 as per initial assignment by Darren .  @xw-g @liulk  @dplore

**Comment by liulk** [comment]
I got a backlog of reviews that I couldn't finish before the weekend. Will continue reviews on Monday.

**Comment by liulk** [comment]
@dplore This seems to be a duplication of effort to #228. To be fair, we had this assigned to a different person in our project view and would be inclined to honor our assignment.

https://github.com/orgs/openconfig/projects/2/views/1

But I also see the merits in this code. How do we want to reconcile the two PRs?

**Comment by dplore** [comment]
@singh-prem thank you for the contribution.  However, this test case development was assigned to @smulky already who submitted pull request #228 as referenced above.  All the planned test development items are tracked in our project page here:  https://github.com/orgs/openconfig/projects/2/views/1.     You can see the specific assignment as a github issue at  #149 

I'm sorry about the conflict and time spent on this development.  We need to consider @smulky 's contribution first.  You can still contribute by reviewing #228 

If you would like to be assigned a test case for development, you can request by filing a github issue and we can assign it.  Or we can have a meeting to discuss it if needed.  I understand @smulky is only just now starting

**Comment by singh-prem** [comment]
Not an issue @dplore ! This was first PR for me as well. I got to know the process for TC development and will follow it. I will surely contribute by reviewing #228 and reach out to you for contributing to TC development.

**Comment by singh-prem** [comment]
please read previous comments

**Pull request closed without merging**
