### PR TITLE
 TE-2.2: moved static route under deviation condition

### PR DESCRIPTION
**Pull request by bkreddy143**
Currently script applying  static route override for all vendor while adding
interface+MAC NextHop instead of restrict to specific deviations.

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Review by NishaSadhasivam-work — DISMISSED** [review]
[test (3).log](https://github.com/openconfig/featureprofiles/files/13658250/test.3.log)
LGTM, PFA the pass log on nokia device.

**Review by Ankur19 — DISMISSED** [review]
LGTM! Can you resolve the merge conflicts

**Comment by LimeHat** [comment]
Thanks Ankur & Nisha,

I removed the README changes (that were causing a conflict) from this PR and kept only the code change to streamline the process.

@Ankur19 let me know if you want us to open another PR with the README update, or if you want to do it yourself. Thanks!

**Review by NishaSadhasivam-work — APPROVED** [review]
[test (5).log](https://github.com/openconfig/featureprofiles/files/13684546/test.5.log)
LGTM!

**Comment by Ankur19** [comment]
> Thanks Ankur & Nisha,
> 
> I removed the README changes (that were causing a conflict) from this PR and kept only the code change to streamline the process.
> 
> @Ankur19 let me know if you want us to open another PR with the README update, or if you want to do it yourself. Thanks!

@LimeHat Thank you for the PR. It would be great if you could also update the Readme.

**Comment by LimeHat** [comment]
Ack, will do

**Pull request merged**
