### PR TITLE
Fixing the attrs.AddToOTG Ipv6 error

### PR DESCRIPTION
**Pull request by octpetre**

### CODE REVIEW

**Review by sezhang2 — APPROVED** [review]

**Review by sezhang2 — CHANGES_REQUESTED** [review]
Please fix the failed checks

**Comment by octpetre** [comment]
@sezhang2 I don;t understand the the static check fails. I changed just one char in one file from **Ipv4Addresses** into **Ipv6Addresses**

**Comment by sezhang2** [comment]
> @sezhang2 I don;t understand the the static check fails. I changed just one char in one file from **Ipv4Addresses** into **Ipv6Addresses**

Let's see the rerun result.

**Comment by octpetre** [comment]
It failed again...but in a different point

**Comment by octpetre** [comment]
I can make the changes in the source branch used in #648

**Review by marcushines — APPROVED** [review]

**Review by sezhang2 — APPROVED** [review]

**Pull request merged**
