### PR TITLE
Update Arista cEOS config for gNMI/gRIBI best practices

### PR DESCRIPTION
**Pull request by liulk**

### CODE REVIEW

**Comment by liulk** [comment]
#128

**Comment by liulk** [comment]
@sulrich I don't know if cEOS supports `hardware fec programmed all` emulation. If not, I'll remove it.

**Comment by sulrich** [comment]
> @sulrich I don't know if cEOS supports `hardware fec programmed all` emulation. If not, I'll remove it.

aiui, there's no equivalent for this with ceos-lab

**Comment by bstoll** [comment]
The "shutdown;no shutdown" etc style commands should not be necessary.  This is loaded as the startup-config on a fresh boot - not changing the configuration after it is already running.  This configuration file is taken from the command "show running-config" (or "write mem") which will never include "shutdown;no shutdown" etc style commands.

I verified AFT streaming works without these changes, so as far as I can tell this doesn't change anything. However, the ordering of the config wasn't exactly right - see [diff](https://github.com/bstoll/featureprofiles/commit/c87bb4b92fe785a92375149e040bc6d652878b0d) that has this fixed up a little bit.  But I don't see any difference in behavior with these changes - it works both before and after.

I left `hardware fec programmed all` out because I don't think it does anything in cEOS, but it does take the command - it should appear after the line `ip routing` if we add it.

**Comment by liulk** [comment]
I removed "shutdown / no shutdown" per your comment, but I moved the provider aft section and hardware fec before the gnmi/gribi sections, so that the statements that would normally require restart of gnmi and gribi would be in place before these agents start.

**Review by bstoll — APPROVED** [review]

**Pull request merged**
