### PR TITLE
changing interface replace call to update

### PR DESCRIPTION
**Pull request by manan-patel**
TE-3.7 base_hierarchical_nhg_update_test.go

After configuring vrf under the interface, making replace call while configuring ip_address overwrites vrf config. Changing the "Replace" call to "update" fixes it.

### CODE REVIEW

**Comment by xw-g** [comment]
internal b/261075541 is driving the merge effort.

**Comment by aredmon8551** [comment]
Just curious is this related to the behavior of deleting L3 addresses from interfaces when those interfaces are mapped to a VRF?

**Comment by sachendras** [comment]
LGTM, more details in b/261075541

**Comment by vosipchu** [comment]
LGTM from me as well.

**Review by vosipchu — APPROVED** [review]

**Review by xw-g — DISMISSED** [review]

**Comment by xw-g** [comment]
@manan-patel can you help solve the merge conflict so we can merge it? Thanks!

**Comment by manan-patel** [comment]
Yes, I'll work on it

**Review by vosipchu — APPROVED** [review]

**Review by xw-g — APPROVED** [review]

**Pull request merged**
