### PR TITLE
Sec-3.1 native user deviation

### PR DESCRIPTION
**Pull request by MarcCharlebois**
1. Allow configuration of users/aaa through native model
2. Add port 57400 for gNMI connection
3. add ssh.Password() auth method
4. Deviation for configuring users/aaa (deviation_set_native_user) 
This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind.

### CODE REVIEW

**Comment by MarcCharlebois** [comment]
@xw-g  there's a failure that seems to be on test metadata, anything I need to action?
```
    case_test.go:156: Errors from check: [`metadata test plan ID needs update: was "YY-1.1", will be "XX-1.1"` `metadata test description needs update: was "Description from Test", will be "Description from Markdown"` `missing testbed in metadata` `bad UUID in metadata: 123e4567-e89b-12d3-a456-426614174000: got variant RFC4122 version 1; want variant RFC4122 version 4`]
```

**Comment by xw-g** [comment]
@MarcCharlebois can you help follow this guidance on the deviation? Thanks! https://github.com/openconfig/featureprofiles/blob/main/internal/deviations/README.md

**Comment by bstoll** [comment]
I think there is a flake on that check - I created #1759 to investigate it more.  A rerun of the check passed - I don't think there is anything specifically wrong with this PR.

**Comment by MarcCharlebois** [comment]
@xw-g - Migrated using the guidance for new deviations, thanks.

**Pull request closed without merging**
