### PR TITLE
P4RT-7.1: add ExplicitInterfaceInDefaultVRF && ExplicitPortSpeed deviations

### PR DESCRIPTION
**Pull request by LimeHat**
Added ExplicitInterfaceInDefaultVRF & ExplicitPortSpeed deviations to configureDUT() function

### CODE REVIEW

**Review by jjing1122 — APPROVED** [review]

**Comment by jjing1122** [comment]
Please Rebase

**Comment by xw-g** [comment]
Since both deviations usage are already approved, I think @jjing1122 can merge this PR.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
