### PR TITLE
TE-11.3: Enabling deviation, updating NH index to integer and adding network-instance for DECAP lookup

### PR DESCRIPTION
**Pull request by trathod1**
There are 2 changes made here -
   1. Enabling following deviations - 
           - `ExplicitInterfaceInDefaultVRF`
           - `ExplicitPortSpeed` 
           - `ExplicitGRIBIUnderNetworkInstance`
   2. Updating static-route NextHop index to an integer

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by xw-g** [comment]
recommended refactor per our offline chat.

**Comment by trathod1** [comment]
Reverted DECAP changes, as they will be handled in PR-1158

**Comment by xw-g** [comment]
I will merge this PR upon my own LGTM because:
* The deviation usage is approved. 
* The changes outside of the deviation gating is also an approved one (see https://github.com/openconfig/featureprofiles/pull/692/files)

**Pull request merged**
