### PR TITLE
TE-3.2: Removing static discard route

### PR DESCRIPTION
**Pull request by trathod1**
Removing the not require static-discard-route.

Reference - https://github.com/openconfig/featureprofiles/pull/1143

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by MarcCharlebois** [comment]
@xw-g , merge conflict was resolved, are we good to merge this one?

**Comment by xw-g** [comment]
@mojiiba, @sgirishj I think we all agree that we don't want static route in this test. So, LGTM to merge?

**Comment by xw-g** [comment]
Archived LGTM from @sachendras

**Review by mojiiba — APPROVED** [review]

**Comment by xw-g** [comment]
Also @mojiiba gaves LGTM offline.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
