### PR TITLE
DP-1.10 - Mixed strict priority and WRR traffic test - Adding required vendor specific queue name change and interface-ref definition 

### PR DESCRIPTION
**Pull request by charantejag504**
DP-1.10 - Mixed strict priority and WRR traffic test - Adding required vendor specific queue name change and interface-ref definition 
1.   Added Queue ID as required by Juniper.
     Other pull request containing such changes: https://github.com/openconfig/featureprofiles/pull/1087. 
     Related OC model change: https://github.com/openconfig/public/pull/772
2.  Included existing deviation ExplicitInterfaceRefDefinition for interface configuration under QoS(classifier and scheduler)

### CODE REVIEW

**Review by greg-dennis — APPROVED** [review]
Approving for Go quality only

**Review by sachendras — APPROVED** [review]

**Pull request merged**
