### PR TITLE
Modifying tolerance value 

### PR DESCRIPTION
**Pull request by RanjithansCisco**
chaning tolerance value for retry scenario

### CODE REVIEW

**Comment by xw-g** [comment]
@vosipchu can you help share your thought first?

**Comment by vbhan-cisco** [comment]
We will split this into 2 PR,  Have opened PR # 1065 to revert the changes , this PR will be modified to take care of tolerance values

**Review by prinikasn — COMMENTED** [review]
Since PR1054 contents were reverted in PR1065, please rebase this and update the description/title to reflect the changes from this PR. I.e increasing loss tolerance.

**Comment by vbhan-cisco** [comment]
Adding a bit higher tolerance is  reliably passing this test,  not sure if there  was a requirement in test to have 2% loss tolerance -  @vosipchu we can discuss  more if required

**Comment by prinikasn** [comment]
For bgp_prefix_limit_test we will be working on a different solution where we will ensure traffic is 100% lost instead of checking with tolerance. Hence closing this PR.

**Pull request closed without merging**
