### PR TITLE
Migrate experimental to new lib

### PR DESCRIPTION
**Pull request by DanG100**
Depends on https://github.com/openconfig/featureprofiles/pull/779

### CODE REVIEW

**Comment by sezhang2** [comment]
There is a build failure:

# github.com/openconfig/featureprofiles/feature/experimental/platform/tests/optics_thresholds_test_test
Error: vet: feature/experimental/platform/tests/optics_thresholds_test/optics_thresholds_test.go:85:58: cannot use transceiverType (constant 15 of type oc.E_PlatformTypes_OPENCONFIG_HARDWARE_COMPONENT) as telemetry.E_PlatformTypes_OPENCONFIG_HARDWARE_COMPONENT value in argument to components.FindComponentsByType
Error: Process completed with exit code 2.

**Review by dan-lepage — APPROVED** [review]
LGTM

**Pull request merged**
