### PR TITLE
DP-1.14: Adding test support for Nokia

### PR DESCRIPTION
**Pull request by trathod1**
Following changes are made in this PR -
    1. Updating deviations in metadata file
    2. Updating test script to support Nokia 

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by rszarecki** [comment]
We must NOT use `FabricPriority` for any other purposes then setting priority of fabric scheduler. In cane of VoQ system this has no sens and should not be done.
Using OpenConfig `fabricPriority` to encode implemetation specific "forwarding-class/traffic-class" index in order to artifically create index-to-OpenConfig_forwarding-group mapping is clear abuse of OpenConfig and Must NOT be done. This mapping, since it has vendor/implemetation specific object shoudl be done either as vendor extension to OpenConfig OR as bootstrap/bootZ configuration.

in OpenConfig `FabricPriority` can only encode what OpenConfig defined - "Set the priority for the forwarding group for local transmission through the device, e.g., across a switching fabric. Higher priorities are considered to be better, such that traffic with fabric priority 128 is considered to be higher priority than that with fabric priority 0."

**Comment by trathod1** [comment]
Updated script to have queue-id configurations as discussed in b/297188157

**Comment by sezhang2** [comment]
Test failed due to unsupported config. I also attached the log file for reference:

[third_party/openconfig/featureprofiles/feature/qos/ate_tests/qos_basic_test/qos_basic_test.go:77](https://cs.corp.google.com/piper///depot/google3/third_party/openconfig/featureprofiles/feature/qos/ate_tests/qos_basic_test/qos_basic_test.go?l=77&ws=sezhang/7932&snapshot=6): Replace(t) on dut(xx34.den85) at /qos: Replace(t) at path origin:"openconfig"  elem:{name:"qos"}: rpc error: code = NotFound desc = error on request {
        prefix:  {
[dp-1.14-fail-nokia.log](https://github.com/openconfig/featureprofiles/files/12552294/dp-1.14-fail-nokia.log)

          target:  "xx34.den85"
        }
        replace:  {
          path:  {
            origin:  "openconfig"
            elem:  {
              name:  "qos"
            }
          }
          val:  {
            json_ietf_val:  "{\n  \"openconfig-qos:forwarding-groups\": {\n    \"forwarding-group\": [\n      {\n        \"config\": {\n          \"name\": \"target-group-BE1\",\n          \"output-queue\": \"BE1\"\n        },\n        \"name\": \"target-group-BE1\"\n      }\n    ]\n  },\n  \"openconfig-qos:queues\": {\n    \"queue\": [\n      {\n        \"config\": {\n          \"name\": \"AF1\",\n          \"queue-id\": 3\n        },\n        \"name\": \"AF1\"\n      },\n      {\n        \"config\": {\n          \"name\": \"AF2\",\n          \"queue-id\": 4\n        },\n        \"name\": \"AF2\"\n      },\n      {\n        \"config\": {\n          \"name\": \"AF3\",\n          \"queue-id\": 5\n        },\n        \"name\": \"AF3\"\n      },\n      {\n        \"config\": {\n          \"name\": \"AF4\",\n          \"queue-id\": 6\n        },\n        \"name\": \"AF4\"\n      },\n      {\n        \"config\": {\n          \"name\": \"BE0\",\n          \"queue-id\": 2\n        },\n        \"name\": \"BE0\"\n      },\n      {\n        \"config\": {\n          \"name\": \"BE1\",\n          \"queue-id\": 1\n        },\n        \"name\": \"BE1\"\n      },\n      {\n        \"config\": {\n          \"name\": \"NC1\",\n          \"queue-id\": 7\n        },\n        \"name\": \"NC1\"\n      }\n    ]\n  }\n}"
          }
        }
        }: Schema '/qos/queues/queue/config' has no local leaf with the name 'queue-id'. Options are [name]: Parse error on line 59:           "name": "NC1",
        Input:
        '{
          "openconfig-qos:forwarding-groups": {
            "forwarding-group": [
              {
                "config": {
                  "name": "target-group-BE1",
                  "output-queue": "BE1"
                },
                "name": "target-group-BE1"
              }
            ]
          },
          "openconfig-qos:queues": {
            "queue": [
              {
                "config": {
                  "name": "AF1",
                  "queue-id": 3
                },
                "name": "AF1"
              },
              {
                "config": {
                  "name": "AF2",
                  "queue-id": 4
                },
                "name": "AF2"
             ...'
--- FAIL: TestBasicConfigWithTraffic (12.92s)
FAIL

**Review by sezhang2 — APPROVED** [review]
Per the discussion, I approve and merge this PR

**Pull request merged**
