### PR TITLE
Remove the recently new added config deleting operation

### PR DESCRIPTION
**Pull request by gforeal**
…config

### CODE REVIEW

**Comment by mojiiba** [comment]
I think the delete should be removed in this code since replace is supposed to replace the existing config and there is not need for delete if replace works as executed.

**Comment by cprabha** [comment]
> I think the delete should be removed in this code since replace is supposed to replace the existing config and there is not need for delete if replace works as executed.

@mojiiba    As counters are being checked before adjacency, delete is required to get consistent counter values without any stale counter.

**Comment by mojiiba** [comment]
> > I think the delete should be removed in this code since replace is supposed to replace the existing config and there is not need for delete if replace works as executed.
> 
> @mojiiba As counters are being checked before adjacency, delete is required to get consistent counter values without any stale counter.

@cprabha i understand your point. But should not also replace clean the counter if the replace is at the container (protocol) level?

**Comment by gforeal** [comment]
Before PR/792, the code actually just doing that - the Replace only.

**Comment by gforeal** [comment]
For Arista EOS, the current delete then replace been handled in the back-end just as-is - first deconfig then config but back to back!

**Comment by gforeal** [comment]
Updated the PR to remove the recently added new deleting operation, thus the sleep is also not necessary anymore, plz review again!

**Comment by nagarushirao** [comment]
pls update the PR description to match the fix

**Comment by gforeal** [comment]
Cisco is the one hard to satisfy so far;
revert the Delete (thus no delay needed anymore) will pass for Arista but fails with Cisco.

**Comment by gforeal** [comment]
By reverting the Delete operation, the test is passing with Arista but still flaky with Cisco mainly in the TestAuthentication section; Cisco team has agreed to address that issue with new PR.

Thanks all for the comments and review!

**Comment by rszarecki** [comment]
What's Juniper view?

**Comment by gforeal** [comment]
The test doesn't have a pass record for Juniper yet, looks it's failing with:

=== RUN   TestBasic/adjacency_state/state/area-address
    third_party/openconfig/featureprofiles/feature/experimental/isis/ate_tests/base_adjacencies_test/base_adjacencies_test.go:243: /network-instances/network-instance[name=DEFAULT]/protocols/protocol[identifier=ISIS][name=DEFAULT]/isis/interfaces/interface[interface-id=et-1/0/0]/levels/level[level-number=2]/adjacencies/adjacency[system-id=6401.0001.0000]/state/area-address: got []string{"49.0001", "49.0002"}, want []string{"49.0002", "49.0001"} (deadline exceeded)

**Comment by cprabha** [comment]
@rszarecki  We prefer keep delete , it cleans up device before beginning with test.  That way it will be inline with other tests like bgp. We can add 5 secs if it is required by other vendors.

**Comment by gforeal** [comment]
@cprabha the change in this PR doesn't have negative impact to Juniper, the tests this change is about are actually passing in Juniper, the current only failure is in the above TestBasic/adjacency_state/state/area-address;

Cisco already stated that the Delete is not supported, and the back to back delete then config has negative impact to Arista.

I'm not sure for which vendor or platform the added Delete is to target to? could you please share if any insight, thanks!

**Comment by vosipchu** [comment]
+1 for @gforeal . Delete is not supported for Cisco and we won't be able to move forward with that. One way or another, Replace will have to be used.

**Review by rszarecki — COMMENTED** [review]
LGTM

**Review by rszarecki — APPROVED** [review]

**Comment by vosipchu** [comment]
LGTM for cisco

**Review by jjing1122 — APPROVED** [review]

**Comment by sachendras** [comment]
LGTM

**Pull request merged**
