### PR TITLE
TE-1.1:adding case insensitive check for mac

### PR DESCRIPTION
**Pull request by bkreddy143**
change validation to ignore  MAC address case while comparing . 

This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an as is basis without any warranties of any kind.

### CODE REVIEW

**Comment by xw-g** [comment]
@bkreddy143 I don't see `checkDUTEntry` func in ATE test here. Do you happen to know why? (which one is more update to date code?)

+ @jasdeep-hundal who is working on ATE -> OTG migration and might have more context.

**Comment by bkreddy143** [comment]
@xw-g , I just glanced through both ate and otg script and looks like ate case validation is happening only in ixia with egress tracking options enabled in flow and in case of otg mac validation is happening in dut and traffic validation is in OTG.  so , OTG has two functions testFlow() and CheckDUTEntry() where as ATE script has only testFlow() .  These changes came from multiple commits .

**Comment by jasdeep-hundal** [comment]
OTG test is more up-to-date here. (I'm not sure the functionality is even available in the ATE version.) The ATE version definitely doesn't meet all the requirements defined the README.

**Comment by bkreddy143** [comment]
do need to update ate_test with checkDUTEntry() ? wanted to know how to proceed on this PR.

**Comment by bkreddy143** [comment]
@xw-g , @jasdeep-hundal  please let me know how to proceed on this PR.

**Review by xw-g — APPROVED** [review]

**Comment by xw-g** [comment]
business logic wise, I think it's ok not to check case sensitivity. @jasdeep-hundal if not other concern, please help merge. Thanks.

**Comment by xw-g** [comment]
no objection from @jasdeep-hundal

**Pull request merged**
