### PR TITLE
adding NI deviation as it was erroneously removed

### PR DESCRIPTION
**Pull request by MarcCharlebois**
"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by xw-g** [comment]
@MarcCharlebois can you help check/clarify which PR erroneously removed it?

**Comment by MarcCharlebois** [comment]
@xw-g, As I had messaged you offline - this is the commit: https://github.com/openconfig/featureprofiles/commit/af7d794edb0cbaaed3865dbb335848aece3d7ef9
Perhaps something went wrong when rebasing the changes and removal was missed.

**Comment by xw-g** [comment]
Thanks for the clarification. Since this is to correct a previous error. I'll merge it upon my own LGTM.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
