### PR TITLE
certZ1.1/1.2-ClientCeritificatesTest revised

### PR DESCRIPTION
**Pull request by priyacj**
Certz 1.1and 1.2 client certificate Tests with reference to https://github.com/priyacj/featureprofiles/blob/main/feature/security/gnsi/certz/client_certificates/README.md

- Incorporated the feedback https://github.com/openconfig/featureprofiles/pull/2488

### CODE REVIEW

**Comment by LimeHat** [comment]
I'm not sure why the new PR was needed (makes hard to track changes). But it doesn't look like this comment was incorporated https://github.com/openconfig/featureprofiles/pull/2488#discussion_r1484908891

**Comment by priyacj** [comment]
> I'm not sure why the new PR was needed (makes hard to track changes). But it doesn't look like this comment was incorporated [#2488 (comment)](https://github.com/openconfig/featureprofiles/pull/2488#discussion_r1484908891)

**Comment by priyacj** [comment]
> I'm not sure why the new PR was needed (makes hard to track changes). But it doesn't look like this comment was incorporated [#2488 (comment)](https://github.com/openconfig/featureprofiles/pull/2488#discussion_r1484908891)

The test flow was fine with the new user credentials with admin privilege for new connection validation post rotating the certificates,  without sharing the vendor credentials .

**Comment by LimeHat** [comment]
> The test flow was fine with the new user credentials with admin privilege for new connection validation post rotating the certificates, without sharing the vendor credentials .

I linked the other comment, not about the credentials :-)

**Pull request closed without merging**
