### PR TITLE
CODEOWNERS add owners for deviations

### PR DESCRIPTION
**Pull request by liulk**

### CODE REVIEW

**Comment by liulk** [comment]
@xw-g: @dplore told me you have had some thoughts about this. Let me know what you think.

**Comment by xw-g** [comment]
Let's discuss it offline first. I think it should include: @vcheny @vosipchu @sachendras @robshakir @xw-g

**Review by robshakir — CHANGES_REQUESTED** [review]
I don't agree with this change. Please let's discuss this further. I'm marking this explicitly as request changes so that it blocks merging.

**Comment by liulk** [comment]
Obsolete by #777

**Pull request closed without merging**
