### PR TITLE
TE-3.1 Base Hierarchical Route Installation

### PR DESCRIPTION
**Pull request by cprabha**
Hi,

This pull resolves new additions to TE-3.1 as in  https://github.com/openconfig/featureprofiles/issues/2224.
Resolves : https://github.com/openconfig/featureprofiles/issues/2224

Thanks,
Prabha

### CODE REVIEW

**Comment by NishaSadhasivam-work** [comment]
The change is failing on cisco with the below error 
configureVrfSelectionPolicyW call in  testRecursiveIPv4EntrywithVrfPolW in failing, 
Please handle the below failure       

 "error-path": "openconfig-network-instance:network-instances/network-instance[name = 'DEFAULT']/policy-forwarding/",
 "error-message": "Invalid interface name",

Log:

[third_party/openconfig/featureprofiles/feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go:599](https://cs.corp.google.com/piper///depot/google3/third_party/openconfig/featureprofiles/feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go?l=599&ws=nsadhasivam/134&snapshot=6): Replace(t) on dut(xx27.den85) at /network-instances/network-instance[name=DEFAULT]/policy-forwarding: Replace(t) at path origin:"openconfig" elem:{name:"network-instances"} elem:{name:"network-instance" key:{key:"name" value:"DEFAULT"}} elem:{name:"policy-forwarding"}: rpc error: code = Internal desc = error on request {
        prefix: {
          target: "xx27.den85"
        }
        replace: {
          path: {
            origin: "openconfig"
            elem: {
              name: "network-instances"
            }
            elem: {
              name: "network-instance"
              key: {
                key: "name"
                value: "DEFAULT"
              }
            }
            elem: {
              name: "policy-forwarding"
            }
          }
          val: {
            json_ietf_val: "{\n  \"openconfig-network-instance:interfaces\": {\n    \"interface\": [\n      {\n        \"config\": {\n          \"apply-vrf-selection-policy\": \"vrf_selection_policy_w\",\n          \"interface-id\": \"HundredGigE0/0/0/25\"\n        },\n        \"interface-id\": \"HundredGigE0/0/0/25\",\n        \"interface-ref\": {\n          \"config\": {\n            \"interface\": \"HundredGigE0/0/0/25\",\n            \"subinterface\": 0\n          }\n        }\n      }\n    ]\n  },\n  \"openconfig-network-instance:policies\": {\n    \"policy\": [\n      {\n        \"config\": {\n          \"policy-id\": \"vrf_selection_policy_w\",\n          \"type\": \"VRF_SELECTION_POLICY\"\n        },\n        \"policy-id\": \"vrf_selection_policy_w\",\n        \"rules\": {\n          \"rule\": [\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_A\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 1\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    10,\n                    18\n                  ],\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 1\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"DEFAULT\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 10\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 10\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"DEFAULT\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 11\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 11\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"DEFAULT\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 12\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 12\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"network-instance\": \"DEFAULT\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 13\n              },\n              \"sequence-id\": 13\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_A\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 2\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    10,\n                    18\n                  ],\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 2\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_A\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 3\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    10,\n                    18\n                  ],\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 3\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_A\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 4\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    10,\n                    18\n                  ],\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 4\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_B\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 5\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    20,\n                    28\n                  ],\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 5\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_B\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 6\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    20,\n                    28\n                  ],\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 6\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_B\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 7\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    20,\n                    28\n                  ],\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 7\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_111\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"ENCAP_TE_VRF_B\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 8\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"dscp-set\": [\n                    20,\n                    28\n                  ],\n                  \"protocol\": 41,\n                  \"source-address\": \"198.51.100.111/32\"\n                }\n              },\n              \"sequence-id\": 8\n            },\n            {\n              \"action\": {\n                \"config\": {\n                  \"decap-fallback-network-instance\": \"TE_VRF_222\",\n                  \"decap-network-instance\": \"DECAP_TE_VRF\",\n                  \"post-decap-network-instance\": \"DEFAULT\"\n                }\n              },\n              \"config\": {\n                \"sequence-id\": 9\n              },\n              \"ipv4\": {\n                \"config\": {\n                  \"protocol\": 4,\n                  \"source-address\": \"198.51.100.222/32\"\n                }\n              },\n              \"sequence-id\": 9\n            }\n          ]\n        }\n      }\n    ]\n  }\n}"
          }
        }
        }: {
         "cisco-grpc:errors": {
          "error": [
           {
            "error-type": "application",
            "error-tag": "bad-element",
            "error-severity": "error",
            "error-path": "openconfig-network-instance:network-instances/network-instance[name = 'DEFAULT']/policy-forwarding/",
            "error-message": "Invalid interface name",
            "error-info": {
             "bad-element": "policy-forwarding"
            }
           }
          ]
         }
        }

**Review by NishaSadhasivam-work — CHANGES_REQUESTED** [review]
The change is failing on cisco with the below error
configureVrfSelectionPolicyW call in testRecursiveIPv4EntrywithVrfPolW in failing,
Please handle the below failure

"error-path": "openconfig-network-instance:network-instances/network-instance[name = 'DEFAULT']/policy-forwarding/",
"error-message": "Invalid interface name",

**Comment by cprabha** [comment]
> The change is failing on cisco with the below error configureVrfSelectionPolicyW call in testRecursiveIPv4EntrywithVrfPolW in failing, Please handle the below failure
> 
> "error-path": "openconfig-network-instance:network-instances/network-instance[name = 'DEFAULT']/policy-forwarding/", "error-message": "Invalid interface name",

updated deviation for cisco.  please check.

**Comment by arulkumarsekar** [comment]
@cprabha is new requirement pr labeled by mistake here? seems to be an existing test.

**Comment by LimeHat** [comment]
> @cprabha is new requirement pr labeled by mistake here? seems to be an existing test.

IMO the answer is no, since the tag is applicable to any new requirement (that can be introduced as a new test or a new/modified item within the existing test)

**Comment by cprabha** [comment]
> @cprabha is new requirement pr labeled by mistake here? seems to be an existing test.

@arulkumarsekar @LimeHat ,  Its an existing test but new testcase added . Hence I have labeled it as new requirement. 
Please check additional scenario as in https://github.com/openconfig/featureprofiles/issues/2224.

Thanks,
Prabha

**Comment by bkreddy143** [comment]
@cprabha , new test addition will result to over all test status as FAIL if this feature is not supported by vendors. Can we add deviation support so that  vendors that doesn't have support can skip the test.

**Comment by cprabha** [comment]
> @cprabha , new test addition will result to over all test status as FAIL if this feature is not supported by vendors. Can we add deviation support so that vendors that doesn't have support can skip the test.

If there is existing deviation, I can add it.

**Comment by bkreddy143** [comment]
> > @cprabha , new test addition will result to over all test status as FAIL if this feature is not supported by vendors. Can we add deviation support so that vendors that doesn't have support can skip the test.
> 
> If there is existing deviation, I can add it.

@cprabha , I don't think there is any deviation readily available as these are new features getting added . Also, it looks like it is not recommended to add isolated deviations unless it is used in in script so better to add sit along with script changes or it needs to be added once this is merged.

**Review by NishaSadhasivam-work — APPROVED** [review]
LGTM!
Works as expected on Juniper device.

**Pull request merged**
