### PR TITLE
moved tests from experimental to feature

### PR DESCRIPTION
**Pull request by self-maurya**

### CODE REVIEW

**Review by rohit-rp — APPROVED** [review]

**Comment by dplore** [comment]
Please also update https://github.com/openconfig/featureprofiles/blob/main/CONTRIBUTING.md to remove the reference to the experimental folder.  Thanks!

**Comment by ram-mac** [comment]
@self-maurya i see the feature.textproto is been deleted. Can you add details on why this file is not needed.
Is this textproto added under some other path?

**Review by ram-mac — APPROVED** [review]
LGTM

**Review by dplore — APPROVED** [review]
This is a good start.  Is there any reason not to move ALL of the tests out of the experimental folder?

**Review by Swetha-haridasula — COMMENTED** [review]
lgtm

**Pull request merged**
