### PR TITLE
change minTraceroutePktSize

### PR DESCRIPTION
**Pull request by Hobbydos**
ref: https://github.com/openconfig/featureprofiles/pull/687

### CODE REVIEW

**Comment by xw-g** [comment]
@bstoll I think this PR itself it's ok because I don't see that the test currently specifies the size. The default value would be upto the system/OS implementation. Raising up the bar here seems fine to me. Also reference https://github.com/openconfig/featureprofiles/pull/687

My question is more about the test itself. The test plan talks about different packet size (not TODO), but I don't see it in the code. Also, I don't see gNOI API supports packet size. Shall we completely remove the mentioning of packet size at all from this test? Thoughts?

**Comment by bstoll** [comment]
I agree that in the current version of this RPC spec it doesn't make a lot of sense to look into the packet size.  It would be useful to be able to specify the packet size but that would be a change to the GNOI spec first before we can test for it.

I think we could completely remove the packet size from this version and tie it as a new feature requiring GNOI spec to be updated first.

**Comment by xw-g** [comment]
Thanks, @bstoll. SGTM. 

@Hobbydos can you help use this PR to remove all the packet size related code and in the README too? Thanks. 

cc: @vcheny @sachendras @vosipchu. We plan to use this PR to remove packet size related tests (README part and code part), because gNOI API currently does not even support it.  See https://github.com/openconfig/featureprofiles/pull/944#issuecomment-1372598410 and https://github.com/openconfig/featureprofiles/pull/944#issuecomment-1374006566 for more context. 

It should have 0 impact on passed tests. Ping me if any objection, otherwise I"ll merge the PR upon my own LGTM.

**Comment by Hobbydos** [comment]
> Thanks, @bstoll. SGTM.
> 
> @Hobbydos can you help use this PR to remove all the packet size related code and in the README too? Thanks.
> 
> cc: @vcheny @sachendras @vosipchu. We plan to use this PR to remove packet size related tests (README part and code part), because gNOI API currently does not even support it. See [#944 (comment)](https://github.com/openconfig/featureprofiles/pull/944#issuecomment-1372598410) and [#944 (comment)](https://github.com/openconfig/featureprofiles/pull/944#issuecomment-1374006566) for more context.
> 
> It should have 0 impact on passed tests. Ping me if any objection, otherwise I"ll merge the PR upon my own LGTM.

Removed pktSize associations to test file and readme file, PTAL and let me know if anything needs changing.

**Comment by Hobbydos** [comment]
@xw-g  @jjing1122 Does this PR look good for merging? Once confirmed, I'll add deviation to this test.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
