### PR TITLE
gNOI-3.2: add check on linecard emptiness

### PR DESCRIPTION
**Pull request by trathod1**
Current version of the test selects the last removable linecard to reboot, however it ignores the empty flag (so it tries to reboot an unpopulated card in some cases). This PR introduces an additional check to skip cards that are not populated

Reference - https://github.com/openconfig/featureprofiles/pull/1127

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

### CODE REVIEW

**Comment by xw-g** [comment]
changes look good, pending presubmit test.

**Comment by MarcCharlebois** [comment]
@xw-g  can we merge this one?

**Comment by xw-g** [comment]
b/271456751 finished the presubmit effort.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
