### PR TITLE
RT-5.4 : Adding ping before traffic test to resolve adjacency

### PR DESCRIPTION
**Pull request by agvarghe-cisco**
- Adding ping before traffic test to resolve adjacency

### CODE REVIEW

**Comment by LimeHat** [comment]
Hey @agvarghe-cisco , I think there could be a simpler approach if we just slightly modify the ATE config steps
What if you modify `configureATE()` function to start protocols in two steps: 1) configure and start LACP, 2) configure and start IPv4/v6, e.g.

Replace lines 337-345 (in the upstream version)
https://github.com/openconfig/featureprofiles/blob/5c85e9ff5a5a9bf1e2b1f4a2050990b90d6a3132/feature/interface/aggregate/ate_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go#L337-L345

to something like this:

```
	tc.top.Push(t).StartProtocols(t)
	agg.IPv4().
		WithAddress(ateDst.IPv4CIDR()).
		WithDefaultGateway(dutDst.IPv4)
	agg.IPv6().
		WithAddress(ateDst.IPv6CIDR()).
		WithDefaultGateway(dutDst.IPv6)
	tc.top.Update(t)
	tc.top.StartProtocols(t)
```

**Comment by guoshiuan** [comment]
b/276496819 has the internal test results.

**Review by guoshiuan — APPROVED** [review]

**Comment by vbhan-cisco** [comment]
@xw-g We will modify the PR and not rely on ping to resolve adjacency, changes that @LimeHat suggested make sense , trying changes  internally . Will be making changes to  PR soon

**Comment by mojiiba** [comment]
it seems the issue is related to ixia and we do not see it with all ixia versions. closing the pr for now to investigate this more.

**Pull request closed without merging**
