### PR TITLE
changed niType to L3VRF and set NextHop to '0' in both ATE/OTG tests

### PR DESCRIPTION
**Pull request by Hobbydos**

### CODE REVIEW

**Comment by Hobbydos** [comment]
Hey @xw-g, I tried sync'ing my fork via the Web GUI and that closed the previous PR. I just reverted back to CLI and just pushed a cleaner PR with changes to both ATE/OTG.

**Comment by robshakir** [comment]
Could you resolve the merge conflicts in this please? I think we're good-to-go after that.

**Comment by Hobbydos** [comment]
> Could you resolve the merge conflicts in this please? I think we're good-to-go after that.

Yep! I'm going through my PRs and was in the process of doing that.

**Comment by xw-g** [comment]
@robshakir @sachendras @vcheny @vosipchu Because this is to fix something that agreed to be fixed but missed (e.g. https://github.com/openconfig/featureprofiles/pull/692), I'm going to merge it upon my own LGTM. Ping me offline if any issues.

**Review by xw-g — APPROVED** [review]

**Pull request merged**
