### PR TITLE
 Bringing down the tolerance to Zero and sending accurate prefixes

### PR DESCRIPTION
**Pull request by RanjithansCisco**
BGP RT 1.5 FP

1)Modified the traffic/flow to send appropriate prefix value for each test case

- First TC (Prefix -1) checks traffic /flow for 200 prefixes instead of 199., hence we see 0.5% of tolerance. So have modified the flow to send appropriate prefix value , similarly for every case via code

2) Tolerance value brought to zero to ensure zero traffic failure

### CODE REVIEW

**Comment by LimeHat** [comment]
So if the expected loss is zero and you propose to use zero tolerance for this test, what is the point in introducing the global argument?

`BGPTrafficTolerance = flag.Int("arg_bgp_tolerance_value", 0, "Allowed tolerance for BGP traffic flow while comparing for pass or fail condition.")`

**Comment by mojiiba** [comment]
> So if the expected loss is zero and you propose to use zero tolerance for this test, what is the point in introducing the global argument?
> 
> `BGPTrafficTolerance = flag.Int("arg_bgp_tolerance_value", 0, "Allowed tolerance for BGP traffic flow while comparing for pass or fail condition.")`

we added it in cases other vendors want to  use that. However, the correct implementation should pass without tolerance.

**Comment by LimeHat** [comment]
> However, the correct implementation should pass without tolerance.

Shouldn't be this a deviation in this case?

**Comment by mojiiba** [comment]
> > However, the correct implementation should pass without tolerance.
> 
> Shouldn't be this a deviation in this case?

sure, we will move this to deviation file

**Review by prinikasn — COMMENTED** [review]
/gcbrun

**Review by prinikasn — APPROVED** [review]

**Pull request merged**
