### PR TITLE
RT-7.5: Remove deviation bgp_conditions_match_community_set_unsupported

### PR DESCRIPTION
**Pull request by yini101**
Remove the deviation 'bgp_conditions_match_community_set_unsupported' and update the way to create match-community-set.

### CODE REVIEW

**Review by self-maurya — APPROVED** [review]

**Comment by dplore** [comment]
@yini101 please resolve conflicts and we can merge this

**Comment by yini101** [comment]
@dplore Thank you for the reminder. I've resolved the merge conflict.

**Review by dplore — APPROVED** [review]

**Pull request merged**
