### PR TITLE
Remove all deviation flag declarations that are moved to metadata proto

### PR DESCRIPTION
**Pull request by prinikasn**
This PR removes all the opensourced deviation flags. 

Please remove any reference to these flags from your test invocation to avoid any test failures.

### CODE REVIEW

**Review by bstoll — COMMENTED** [review]
Shouldn't all the references to `logErrorIfFlagSet()` also be removed?  It won't be possible to set the flag values once the flags are removed.

**Comment by greg-dennis** [comment]
>

**Comment by greg-dennis** [comment]
Inadvertent click, sorry

**Comment by prinikasn** [comment]
> Shouldn't all the references to `logErrorIfFlagSet()` also be removed? It won't be possible to set the flag values once the flags are removed.

Agreed, initially thought of doing this in a later PR, but it makes more sense to just add it in this PR. Thank you for pointing it out!

**Review by greg-dennis — APPROVED** [review]

**Pull request merged**
