### PR TITLE
gNOI-3.4: fix gnoi path for component and reboot status with empty subcomponent 

### PR DESCRIPTION
**Pull request by mojiiba**
This pull adds two deviations and change the gNOI-3.4 accordingly.
- GNOISubcomponentPath: based on the GNOI spec we need to use path to refer to sub-components. However, the existing tests only uses a path with a single element and no key to refer to sub-component. IMO, this does not seem to be complied with the spec. This deviation will allow us to use fully OC complied path for the component.
- GNOIStatusWithEmptySubcomponent: as discussed https://github.com/openconfig/gnoi/issues/54 and https://github.com/openconfig/gnoi/pull/99, the gNOI reboot status command response is singular value and therefore it is not clear what the device should reply to a status command when the subcomponent is not set and there are more than one active reboot.

### CODE REVIEW

**Review by sezhang2 — DISMISSED** [review]

**Comment by sezhang2** [comment]
Please re-sync your code to resolve the conflict.

**Comment by mojiiba** [comment]
> Please re-sync your code to resolve the conflict.

thanks, done

**Comment by mojiiba** [comment]
@sezhang2 can u please merge this pr?

**Comment by sezhang2** [comment]
> @sezhang2 can u please merge this pr?

Will merge after all checks pass.

**Review by sezhang2 — APPROVED** [review]

**Comment by mojiiba** [comment]
> > @sezhang2 can u please merge this pr?
> 
> Will merge after all checks pass.

thanks a lot!

**Pull request merged**
