### PR TITLE
P4RT-1.1 , update DUT links from 2 to 4

### PR DESCRIPTION
**Pull request by rsindhujha**
Changed metadata.textproto from TESTBED_DUT_ATE_2LINKS to TESTBED_DUT_ATE_4LINKS, to have a better chance of different nodes getting selected during run.

### CODE REVIEW

**Review by sachendras — APPROVED** [review]

**Comment by LimeHat** [comment]
@rsindhujha you're modifying p4rt-2.1 instead of p4rt-1.1 (which is stated in the subject). Is this intended?

**Comment by rsindhujha** [comment]
> @rsindhujha you're modifying p4rt-2.1 instead of p4rt-1.1 (which is stated in the subject). Is this intended?

Thanks for pointing out @LimeHat. My bad, modified the wrong file. Fixed it now.

**Review by greg-dennis — APPROVED** [review]
Approving for Go quality (there is no Go code here)

**Review by greg-dennis — CHANGES_REQUESTED** [review]
Actually, hold on, I'm not sure the point of this PR. The testbed should specify what the test requires, and this test only request 2 links, right?

**Comment by rsindhujha** [comment]
> Actually, hold on, I'm not sure the point of this PR. The testbed should specify what the test requires, and this test only request 2 links, right?

On Juniper ptx10001, with 2 port topology there are  chances that both ports are picked from the same FAP. To help ports getting picked from multiple FAPs increasing it to 4 port topology helps.

**Comment by sachendras** [comment]
We are fixing this internally hence the pull is not required anymore, closing!

**Pull request closed without merging**
